export const words = {
    "Portugues": [
        "abastecer", "aberto", "abraço", "abril", "abrir",
        "absoluto", "acabar", "aceitar", "acerca", "achado",
        "achar", "acima", "acordar", "acordo", "acreditar",
        "acrescentar", "actividade", "actual", "açúcar", "acusar",
        "adaptar", "adiante", "adicionar", "admitir", "adorar",
        "adormecer", "adulto", "adversário", "afastar", "afirmar",
        "afinal", "agarrar", "agora", "agosto", "agradar",
        "agradecer", "água", "aguentar", "agudo", "agulha",
        "ajudar", "ajuste", "alargar", "alegre", "alegria",
        "além", "alface", "algo", "algodão", "alguém",
        "algum", "algures", "alheio", "ali", "aliás",
        "alimento", "almoço", "alojamento", "alongar", "alto",
        "altura", "alugar", "aluno", "alvo", "amanhã",
        "amar", "amarelo", "amargo", "ambiente", "ameaça",
        "ameixa", "amigo", "amizade", "amor", "amostra",
        "amplo", "analisar", "análise", "ancorar", "andar",
        "anel", "anexo", "animal", "aniversário", "ano",
        "anotar", "ansiedade", "anteontem", "anterior", "antes",
        "antigo", "anunciar", "anúncio", "anzol", "ao",
        "apagar", "apaixonado", "apanhar", "aparelho", "aparentar",
        "apartamento", "aparte", "apelido", "apenas", "apertar",
        "apesar", "apetite", "apitar", "apoio", "apontar",
        "aprender", "apresentar", "aproveitar", "aproximar", "aptidão",
        "aquele", "aquecer", "aqui", "aquilo", "ar",
        "aranha", "armazém", "armário", "arrancar", "arranjar",
        "arrumar", "arte", "artigo", "árvore", "asa",
        "aspeto", "assado", "assaltar", "assunto", "assustar",
        "atacar", "ataque", "atrás", "atrasar", "através",
        "atrelado", "atrever", "atribuir", "atualizar", "atuação",
        "aula", "aumento", "ausência", "autor", "autoridade",
        "auxiliar", "avançar", "avaria", "ave", "avenida",
        "aventura", "avião", "aviso", "avó", "avô",
        "azeite", "azeitona", "azul", "bacalhau", "bacia",
        "bafo", "bagagem", "bairro", "baixa", "baixo",
        "balança", "balão", "balde", "baliza", "banco",
        "banda", "bandeira", "banho", "baralho", "barato",
        "barba", "barco", "barulho", "barriga", "barro",
        "base", "bastante", "bastar", "batalha", "batata",
        "bater", "batom", "baú", "beber", "bebida",
        "beijo", "beira", "beleza", "bem", "bênção",
        "benéfico", "bens", "berço", "besta", "beterraba",
        "bexiga", "biblioteca", "bica", "bicho", "bicicleta",
        "bife", "bigode", "bilhete", "binóculo", "biologia",
        "biscoito", "bispo", "bitoque", "bloco", "blusa",
        "boa", "boca", "bocado", "bocejo", "boda",
        "bofetada", "boi", "boia", "bola", "bolacha",
        "bolo", "bolsa", "bolso", "bom", "bomba",
        "bombeiro", "bondade", "boné", "boneca", "bonito",
        "bordo", "borracha", "borrego", "bota", "botão",
        "boteco", "botija", "braço", "bradar", "branco",
        "brando", "brasa", "bravo", "breve", "brigar",
        "brilhar", "brilho", "brincar", "brinde", "brinquedo",
        "brisa", "broa", "broca", "bronze", "bruxa",
        "buraco", "burro", "busca", "buzina", "cabaça",
        "cabaço", "cabaia", "cabal", "cabana", "cabeça",
        "cabelo", "cabina", "cabo", "cabrito", "caça",
        "caçamba", "caçador", "caçar", "cacau", "cacho",
        "cachorro", "cacifo", "cacimba", "cada", "cadela",
        "caderno", "cadeira", "cadência", "cais", "caixa",
        "caixote", "cajado", "caju", "cal", "calada",
        "calado", "calamidade", "calão", "calça", "calçado",
        "calcanhar", "calças", "calçada", "calcular", "cálculo",
        "calda", "caldeira", "caldo", "calecer", "calha",
        "calhau", "calma", "calmante", "calmo", "caloiro",
        "calor", "calos", "calote", "caluda", "calúnia",
        "calvário", "cama", "camada", "camarada", "camarão",
        "cambalhota", "câmbio", "caminhada", "caminho", "camião",
        "camisa", "camisola", "campa", "campainha", "campismo",
        "campo", "camponês", "canal", "canário", "canção",
        "caneca", "canela", "caneta", "canga", "canhão",
        "canhoto", "canil", "canivete", "cano", "canoa",
        "cansaço", "cansado", "cansar", "cantar", "cantiga",
        "canto", "cantor", "canudo", "cão", "capa",
        "capaz", "capela", "capitão", "capítulo", "capota",
        "capricho", "captar", "capuz", "cara", "caracol",
        "caráter", "caravana", "carbono", "carcaça", "cardápio",
        "cardeal", "carga", "cargo", "caridade", "carimbo",
        "carinho", "carismático", "carne", "carneiro", "caro",
        "caroço", "carona", "carpa", "carpinteiro", "carregar",
        "carreira", "carrelo", "carreta", "carrinho", "carro",
        "carroça", "carruagem", "carta", "cartão", "cartaz",
        "carteira", "carteiro", "cartucho", "carvão", "casa",
        "casaco", "casal", "casamento", "casar", "casca",
        "cascalho", "casco", "caseiro", "caserna", "casinha",
        "caso", "caspa", "castanha", "castanho", "castelo",
        "castigo", "catálogo", "catarata", "catedrático", "categoria",
        "católico", "cauda", "causa", "causar", "cautela",
        "cavaleiro", "cavalo", "caverna", "cavidade", "cebola",
        "cedo", "cédula", "cegar", "cego", "ceia",
        "ceifa", "cela", "celeiro", "celebrar", "celeste",
        "celular", "cem", "cena", "cenário", "cenoura",
        "censo", "centavo", "centeio", "centena", "central",
        "centro", "cera", "cerâmica", "cerca", "cercar",
        "cerco", "cereais", "cereja", "cerimónia", "cerne",
        "cerrado", "certame", "certamente", "certeza", "certidão",
        "certificado", "certo", "cerveja", "cesto", "cetim",
        "céu", "chá", "chácara", "chaga", "chaleira",
        "chama", "chamada", "chamar", "chaminé", "chão",
        "chapa", "chapéu", "charco", "charme", "charuto",
        "chata", "chato", "chave", "chávena", "chefe",
        "chegada", "chegar", "cheio", "cheirar", "cheiro",
        "cheque", "chicote", "chifre", "chinelo", "chique",
        "chispa", "chocalho", "choque", "choro", "chover",
        "chuva", "chouriço", "churrasco", "chutar", "cicatriz",
        "cidade", "ciência", "ciente", "cifra", "cigano",
        "cigarro", "cilindro", "cima", "cimento", "cinto",
        "cinza", "cinzento", "ciúme", "civil", "clareza",
        "claro", "classe", "clássico", "cláusula", "clero",
        "cliente", "clima", "clínica", "clube", "coar",
        "cobalto", "cobertura", "cobiça", "cobra", "cobrador",
        "cobrança", "cobrar", "cobre", "cobrir", "coceira",
        "cocho", "coelho", "coesão", "cofre", "cogumelo",
        "coice", "coincidir", "coisa", "coitado", "cola",
        "colaborar", "colagem", "colar", "colcha", "colchão",
        "colega", "colégio", "coleira", "colheita", "colher",
        "colina", "colisão", "colmeia", "colo", "colocado",
        "colocar", "colónia", "coluna", "com", "coma",
        "comadre", "comando", "comarca", "combate", "combinação",
        "comboio", "começar", "começo", "comédia", "comemorar",
        "comentário", "comer", "comercial", "comércio", "cometa",
        "comida", "comício", "comigo", "comissão", "comité",
        "como", "cómodo", "comover", "compacto", "compaixão",
        "companheiro", "companhia", "comparar", "compaixão", "compasso",
        "compatível", "compilar", "compadre", "compensar", "competir",
        "complexo", "complicar", "compor", "comportar", "compositor",
        "composto", "compra", "comprar", "comprido", "comprimento",
        "compromisso", "comum", "comuna", "comunicar", "comunidade",
        "comunhão", "conceito", "concelho", "conceder", "concentrar",
        "concepção", "concha", "concluir", "concordar", "concreto",
        "concurso", "condado", "condição", "condutor", "conduzir",
        "cone", "confeção", "conferência", "confessar", "confiança",
        "confiar", "confinar", "confirmar", "conflito", "conforme",
        "conforto", "confuso", "congelar", "congratular", "conhecer",
        "conjunto", "connosco", "conquista", "consciência", "conseguir",
        "conselho", "conserto", "conservar", "considerar", "consigo",
        "consistir", "consolo", "consoante", "conspiração", "constante",
        "constituir", "construtor", "construir", "consulado", "consultar",
        "consumo", "conta", "contacto", "contar", "contemplar",
        "conter", "contente", "contestar", "contigo", "continente",
        "continuar", "contínuo", "conto", "contra", "contrário",
        "contraste", "contrato", "contribuir", "controlo", "convencer",
        "convénio", "conversa", "converter", "convidado", "convite",
        "conviver", "copa", "cópia", "copo", "cor",
        "coração", "coragem", "corar", "corda", "cordeiro",
        "cordial", "corno", "coro", "coroa", "corpo",
        "corredor", "córrego", "correia", "correio", "correr",
        "corrida", "corrigir", "corromper", "cortar", "corte",
        "cortesia", "cortina", "coruja", "coser", "costa",
        "costas", "costuma", "costume", "costura", "cota",
        "cotovelo", "couro", "couve", "cova", "coxo",
        "cozinha", "cozer", "crânio", "creche", "crédito",
        "creme", "crença", "crente", "crer", "crescer",
        "crescido", "criada", "criado", "criança", "criar",
        "criativo", "crime", "crise", "cristal", "critério",
        "crítica", "crítico", "crivo", "crónico", "cronómetro",
        "cru", "crucial", "crueza", "cruzar", "cruzeiro",
        "cubo", "cuidado", "cuidar", "culpar", "culto",
        "cultura", "cumprir", "cunhado", "cupão", "cura",
        "curar", "curiosidade", "curioso", "curral", "curso",
        "curto", "curva", "curvado", "custar", "custo",
        "cutelo", "dado", "dama", "dança", "dançar",
        "dano", "daquela", "daquele", "daqui", "dar",
        "data", "debaixo", "debate", "debitar", "débito",
        "decada", "decaer", "decente", "decepção", "decidir",
        "décimo", "decisão", "declarar", "declive", "decorar",
        "decorrer", "decreto", "dedo", "deduzir", "defesa",
        "deferir", "defesa", "definir", "defunto", "degelo",
        "degrau", "deitado", "deitar", "deixar", "delatado",
        "delegacia", "delegado", "deleitar", "delfim", "delgado",
        "delicado", "delícia", "demais", "demanda", "demasiado",
        "demitir", "democracia", "demonstrar", "demora", "dengoso",
        "denso", "dentado", "dente", "dentista", "dentro",
        "denúncia", "depressa", "deputado", "derivar", "derramar",
        "derreter", "derrotar", "deriva", "desafio", "desaguar",
        "desânimo", "desaparecer", "desarmar", "desastre", "desatar",
        "desbastar", "descansar", "descarregar", "descida", "descoberta",
        "descontar", "descrever", "desculpar", "desde", "desejar",
        "desenhar", "desenho", "deserto", "desespero", "desfilar",
        "desgaste", "designar", "desistir", "deslizar", "deslocar",
        "desmaio", "desmentir", "despacho", "despedida", "despeito",
        "despensa", "desperta", "despesa", "desporto", "destaque",
        "destino", "destra", "destruir", "desviar", "detalhe",
        "deter", "deteriorar", "determinar", "detestar", "detrás",
        "deusa", "devagar", "devedor", "dever", "devido",
        "devolver", "devoto", "dez", "dezena", "dezembro",
        "dia", "diabo", "diadema", "diagrama", "dialeto",
        "diálogo", "diamante", "diante", "diário", "diarreia",
        "dica", "dieta", "difícil", "difundir", "digerir",
        "digital", "dignidade", "digno", "dilatar", "dilema",
        "diluente", "diluído", "dimensão", "diminuir", "dinâmico",
        "dinheiro", "dino", "diocese", "diploma", "direção",
        "direita", "direito", "diretor", "dirigir", "disfarce",
        "disparo", "dispor", "disposto", "disputa", "distância",
        "distinto", "distrito", "distúrbio", "ditar", "ditoso",
        "diurno", "dividir", "divino", "divisar", "divisão",
        "divórcio", "divulgar", "dizer", "dobra", "dobrar",
        "doce", "doçura", "doença", "doente", "doer",
        "dois", "domar", "dominar", "domingo", "domínio",
        "dona", "donatário", "donde", "dono", "dor",
        "dormir", "dorso", "dosagem", "dose", "dotação",
        "dotar", "doutor", "doutrina", "doze", "dragão",
        "drama", "drenar", "droga", "duas", "dublagem",
        "ducha", "duelo", "dueto", "duplo", "duque",
        "durante", "durar", "dureza", "duro", "dúvida",
        "duvidoso", "duzentos", "eclético", "eclodir", "eco",
        "escola", "economia", "ecrã", "edital", "edifício",
        "editor", "educar", "efetivo", "eficaz", "efusivo",
        "egípcio", "egoísta", "eixo", "elaborar", "elástico",
        "eleger", "eleição", "eleito", "elemento", "elenco",
        "elevado", "elevar", "eliminar", "elogiar", "elogio",
        "elucidar", "embaixada", "embalagem", "embora", "embuço",
        "emenda", "emergência", "emitir", "emoção", "empada",
        "empate", "empenho", "emprego", "empresa", "emprestar",
        "empurrar", "encanto", "encargo", "encher", "encontro",
        "endereço", "energia", "enfrentar", "engano", "engenheiro",
        "engolir", "engraçado", "enigma", "enorme", "enquanto",
        "ensinar", "ensino", "então", "entender", "entidade",
        "entrada", "entrar", "entre", "entregar", "entrevista",
        "enviar", "envolver", "enxada", "enxame", "enxerto",
        "época", "equipa", "equívoco", "erguer", "errado",
        "errar", "erro", "ervilha", "escada", "escama",
        "escândalo", "escapar", "esclarecer", "escola", "escolha",
        "escolher", "esconder", "escova", "escravo", "escrever",
        "escrito", "escritório", "escudo", "escuro", "escusa",
        "esforço", "esfomeado", "esfregar", "esgotar", "esgrima",
        "espaço", "espada", "espalhar", "espanto", "espátula",
        "especial", "espelho", "espera", "esperança", "esperar",
        "esperto", "espesso", "espetáculo", "espeto", "espiga",
        "espinha", "espinho", "espírito", "espirrar", "esponja",
        "esposa", "esposo", "esquina", "esquerda", "esquerdo",
        "esse", "essência", "essencial", "estabelecer", "estação",
        "estádio", "estado", "estadia", "estágio", "estalar",
        "estampa", "estância", "estante", "estar", "estátua",
        "estatura", "estável", "este", "esteira", "estender",
        "estereotipo", "estilo", "estimar", "estímulo", "estrada",
        "estrangeiro", "estranho", "estratégia", "estreito", "estrela",
        "estremecer", "estreia", "estrito", "estudar", "estudante",
        "estúdio", "estudo", "estufa", "estúpido", "etapa",
        "etiqueta", "eu", "evidência", "evitar", "evoluir",
        "exagero", "exaltar", "exame", "examinar", "exato",
        "exceder", "excelente", "exceção", "excesso", "excluir",
        "excursão", "execução", "exemplo", "exercício", "exibir",
        "exigir", "exílio", "existir", "êxito", "expedir",
        "expulso", "experiência", "explicar", "explorar", "expor",
        "expressão", "extensão", "exterior", "externo", "extra",
        "extrair", "extremo", "fábrica", "fabrico", "fábula",
        "faca", "façanha", "facho", "fácil", "faculdade",
        "fada", "fadiga", "fado", "faixa", "fala",
        "falar", "falecer", "falha", "falhar", "falir",
        "falso", "falta", "faltar", "fama", "família",
        "famoso", "fanático", "fango", "fantasia", "fantasma",
        "farda", "farelo", "farinha", "faro", "farol",
        "farpado", "farta", "farto", "fartura", "fase",
        "fastio", "fatia", "fátima", "fato", "fatura",
        "fauce", "fauna", "favor", "favorito", "faxina",
        "fazenda", "fazer", "fé", "fealdade", "febre",
        "fechado", "fechar", "fecho", "fecundo", "federação",
        "feder", "feição", "feio", "feira", "feitiço",
        "feitio", "feito", "feitor", "feijão", "feixe",
        "felicidade", "felicitar", "feliz", "felpa", "feltro",
        "fêmea", "fenda", "fender", "feno", "fera",
        "feroz", "ferradura", "ferragem", "ferramenta", "ferrão",
        "ferrar", "ferreiro", "ferro", "ferrovia", "ferver",
        "festa", "festejar", "fevereiro", "fiado", "fiança",
        "fiar", "fibra", "ficar", "ficção", "ficha",
        "fidalgo", "fiel", "figa", "fígado", "figo",
        "figura", "fila", "filamento", "fileira", "filha",
        "filho", "filme", "filosofia", "filtrar", "fim",
        "fina", "final", "finanças", "findar", "fineza",
        "fingir", "finito", "fino", "finta", "fio",
        "firma", "firme", "fiscal", "fita", "fivela",
        "fixar", "fixo", "flanco", "flauta", "flecha",
        "flexível", "flor", "florescer", "floresta", "fluir",
        "foca", "foco", "fofoca", "fofo", "fogo",
        "fogueira", "foguete", "foice", "folclore", "folga",
        "folha", "folheto", "fome", "fomentar", "fona",
        "fonte", "fora", "força", "forçar", "forense",
        "forja", "forma", "formar", "formato", "formiga",
        "formoso", "fórmula", "fornecer", "forno", "foro",
        "forra", "forro", "forte", "fortuna", "fórum",
        "fosco", "fósforo", "fossa", "facto", "foto",
        "fatia", "frouxo", "fruta", "fuga", "fumo",
        "fundo", "furar", "futebol", "futuro", "gado",
        "gafanhoto", "gaiola", "gaita", "gala", "galão",
        "galar", "galinha", "galo", "galopar", "gancho",
        "ganhar", "ganho", "garagem", "garfo", "garganta",
        "garra", "garrafa", "gás", "gastar", "gasto",
        "gato", "gavea", "gaveta", "gelado", "gelar",
        "geleia", "gelo", "gema", "gemer", "gémeo",
        "general", "género", "genro", "gente", "gentil",
        "geral", "gerar", "gerência", "gerir", "gesso",
        "gesto", "gigante", "ginásio", "girar", "giro",
        "giz", "globo", "glória", "golo", "golpe",
        "goma", "gordo", "gordura", "gorgear", "gosto",
        "gostar", "gota", "governo", "gozo", "grade",
        "grado", "grama", "gramática", "grande", "granito",
        "grão", "grátis", "grau", "gravar", "grave",
        "gravura", "greve", "grelha", "gritar", "grito",
        "grosso", "grudar", "grupo", "guarda", "guardar",
        "guerra", "guia", "guiar", "guizo", "habilidade",
        "habitação", "hábito", "hálito", "harmonia", "haste",
        "haver", "hectare", "herança", "herói", "hiato",
        "higiene", "hino", "hipótese", "história", "hoje",
        "holandês", "homem", "homenagem", "honra", "hora",
        "horário", "horizonte", "hospital", "hotel", "humanidade",
        "humilde", "humor", "iate", "idade", "ideal",
        "ideia", "identificar", "idioma", "ídolo", "idoso",
        "igreja", "igual", "ilha", "iludir", "iluminar",
        "ilustrar", "imagem", "imaginar", "imediato", "imenso",
        "imitar", "imóvel", "ímpar", "impasse", "impedir",
        "império", "implicar", "impor", "importante", "imposto",
        "imprensa", "imprimir", "improviso", "imundo", "imunidade",
        "incêndio", "incerto", "inchar", "incidir", "incluir",
        "incomodar", "incrível", "indicar", "índice", "indireto",
        "indivíduo", "indústria", "infante", "inferior", "infinito",
        "inflação", "influência", "informar", "inglês", "ingrato",
        "iniciar", "inimigo", "injúria", "inimigo", "insistir",
        "instante", "instrução", "insultar", "inteiro", "inteligente",
        "intenção", "interior", "interno", "intitular", "inútil",
        "inventar", "inverno", "investir", "inveja", "invés",
        "irmã", "irmão", "isca", "isento", "isolado",
        "isolar", "isqueiro", "item", "itinerário", "jacaré",
        "jacente", "jacto", "jamais", "janela", "jantar",
        "jardim", "jardineiro", "jarra", "jato", "jaula",
        "jazigo", "jeito", "jejum", "joelho", "jogador",
        "jogar", "jogo", "joia", "jornal", "jovem",
        "juiz", "juízo", "julgar", "julho", "junho",
        "juntar", "junto", "jurado", "jurar", "juro",
        "justiça", "justo", "juvenil", "labareda", "lábio",
        "labor", "laço", "lacuna", "lado", "ladrão",
        "ladrilho", "lagarta", "lago", "lagoa", "lagosta",
        "lágrima", "laje", "lama", "lâmina", "lâmpada",
        "lança", "lançar", "lanche", "lancha", "lápis",
        "lar", "laranja", "lareira", "largada", "largo",
        "largura", "lata", "latão", "latir", "latoeiro",
        "laudo", "lavagem", "lavar", "lavoura", "lazer",
        "leal", "leão", "lebre", "lecionar", "legação",
        "legado", "legal", "legenda", "legítimo", "legume",
        "lei", "leigo", "leilão", "leite", "leito",
        "leitor", "leitura", "lembrar", "leme", "lençol",
        "lenda", "lenha", "lenço", "lento", "lente",
        "leque", "ler", "lesão", "leste", "letra",
        "levantar", "levar", "leve", "liberdade", "libra",
        "lição", "licença", "licor", "lida", "lidar",
        "liga", "ligar", "ligeiro", "lilás", "lima",
        "limão", "limiar", "limitar", "limite", "limonada",
        "limpa", "limpeza", "limpo", "lindo", "língua",
        "linha", "linho", "líquido", "lira", "lírio",
        "liso", "lista", "listra", "litro", "livre",
        "livro", "lixo", "loba", "lobo", "local",
        "locutor", "lodo", "lógica", "logo", "loja",
        "lombo", "lona", "longe", "longo", "lontra",
        "loquaz", "lote", "louça", "louco", "loucura",
        "louvor", "lua", "luar", "lucro", "lugar",
        "lume", "luminoso", "lunar", "lupa", "luta",
        "lutar", "luva", "luz", "má", "macaco",
        "maçã", "machado", "macho", "macio", "madeira",
        "madrugada", "mãe", "maestro", "magia", "mágico",
        "magro", "maio", "maior", "mais", "mal",
        "mala", "maldade", "malha", "malta", "mamar",
        "manada", "mancha", "mandar", "maneira", "manga",
        "manha", "manhã", "mania", "manilha", "manso",
        "manteiga", "manter", "manto", "mão", "mapa",
        "máquina", "mar", "marca", "março", "maré",
        "marfim", "margarida", "margem", "marido", "marinha",
        "marisco", "mármore", "marquês", "marreta", "martelo",
        "mas", "massa", "mastigar", "mata", "matar",
        "matemática", "matéria", "matinal", "mato", "matriz",
        "maturo", "máximo", "meandro", "mear", "mecanismo",
        "mecha", "medalha", "média", "medicina", "médico",
        "medida", "medir", "medo", "meia", "meigo",
        "meio", "mel", "melado", "melancia", "melão",
        "melhor", "melodia", "membro", "menina", "menino",
        "menor", "menos", "mensagem", "mental", "mente",
        "mentir", "mentira", "menu", "mercado", "mercearia",
        "merecer", "mergulhar", "mérito", "mês", "mesa",
        "mesmo", "mestre", "metade", "metal", "meter",
        "método", "metro", "meu", "mexer", "meio",
        "migalha", "mil", "milagre", "milhão", "milho",
        "militar", "mimo", "mina", "mínimo", "ministro",
        "minuto", "misto", "mistura", "mito", "miúdo",
        "moda", "modelo", "modesto", "modo", "moeda",
        "moer", "mofo", "mola", "moldura", "mole",
        "molhar", "molho", "momento", "monarca", "monge",
        "montanha", "montar", "monte", "morada", "morango",
        "morar", "morder", "moreno", "morrer", "morte",
        "morto", "mosca", "mostarda", "mostrar", "motivo",
        "motor", "móvel", "mudar", "mudo", "muito",
        "mula", "multa", "mundo", "muralha", "muro",
        "músculo", "museu", "música", "musselina", "mutilar",
        "mútuo", "nação", "nada", "nadar", "nádegas",
        "naipes", "namorar", "não", "nariz", "nascer",
        "natal", "natura", "navalha", "navegar", "navio",
        "negar", "negócio", "negro", "nem", "nenhum",
        "nervo", "neto", "neve", "ninho", "nível",
        "nó", "noite", "noivo", "nome", "nona",
        "nora", "norma", "norte", "nós", "nota",
        "notar", "notícia", "nova", "nove", "novelo",
        "novembro", "novo", "noz", "nu", "nuance",
        "nuvem", "número", "nunca", "nupcial", "nutrir",
        "oasís", "obcecado", "obedecer", "objetivo", "objeto",
        "obra", "obrigado", "obrigar", "obscuro", "observar",
        "obter", "obvio", "ocasião", "oceano", "ocidente",
        "ócio", "oco", "ocorrer", "óculos", "ocupar",
        "odiar", "oeste", "ofender", "oferenda", "oferta",
        "oficial", "oficina", "ofício", "ofuscante", "oitavo",
        "oito", "óleo", "olhar", "olho", "oliva",
        "ombro", "omissão", "onda", "onde", "ontem",
        "onze", "opção", "operação", "operário", "opinar",
        "oportuno", "oposto", "ora", "oração", "orar",
        "ordem", "ordenar", "orelha", "orgulho", "orientar",
        "origem", "original", "orla", "ornar", "órfão",
        "osso", "ostra", "ou", "ouro", "ousar",
        "outono", "outra", "outro", "outubro", "ouvido",
        "ouvir", "ovo", "oxigénio", "paciência", "pacífico",
        "pacote", "pacto", "padaria", "padeiro", "padrão",
        "padrinho", "padre", "pagamento", "pagar", "página",
        "pai", "painel", "país", "paisagem", "paixão",
        "pala", "palácio", "palavra", "palco", "palha",
        "palhaço", "palito", "palma", "palmeira", "palpitar",
        "pancada", "pânico", "pano", "pântano", "pão",
        "papa", "papagaio", "papel", "par", "para",
        "parabéns", "paragem", "parar", "parceiro", "parceria",
        "pardo", "parecer", "parede", "parente", "paridade",
        "parque", "parte", "partida", "partir", "parto",
        "parvo", "pasmar", "pasmo", "passado", "passageiro",
        "passar", "pássaro", "passear", "passeio", "passo",
        "pasta", "pastel", "pata", "patas", "pátio",
        "patrão", "pátria", "património", "pato", "pausa",
        "pau", "pavão", "pavio", "paz", "pé",
        "peão", "peça", "pecado", "pedaço", "pedido",
        "pedir", "pedra", "pegar", "peito", "peixe",
        "pele", "pelo", "pena", "penca", "pendurar",
        "penedo", "penhor", "penso", "pente", "pequeno",
        "pera", "perante", "perca", "perceber", "percorrer",
        "perda", "perder", "perto", "peruca", "pesado",
        "pesar", "pesca", "pescoço", "peso", "pesquisa",
        "pêssego", "pessoal", "pessoa", "petisco", "petróleo",
        "piada", "piano", "picada", "pico", "piedade",
        "pilar", "pilha", "piloto", "pimenta", "pincel",
        "pinga", "pingo", "pinha", "pinheiro", "pinto",
        "pintor", "pintura", "pior", "pipa", "pique",
        "pirâmide", "pires", "pirata", "pisa", "piso",
        "pista", "pito", "pivô", "pizza", "placa",
        "plano", "planta", "plantar", "plasma", "plástico",
        "plataforma", "pleito", "pleno", "pluma", "pneu",
        "pó", "pobre", "poço", "poder", "poema",
        "poesia", "poeta", "pois", "polimento", "política",
        "polo", "polpa", "polvo", "poma", "pomar",
        "pomba", "pombo", "pompa", "ponche", "ponta",
        "ponte", "ponto", "população", "por", "porão",
        "porca", "porco", "porém", "pormenor", "porta",
        "portão", "porto", "português", "porventura", "posse",
        "possível", "postal", "posto", "pouco", "poupar",
        "pousar", "povo", "praça", "prado", "praga",
        "praia", "prancha", "prata", "prato", "prazer",
        "prazo", "preço", "precisar", "prédio", "prefeito",
        "pregar", "prego", "prejuízo", "prenda", "prender",
        "preocupar", "preparar", "presença", "presente", "presunto",
        "preto", "prever", "primavera", "primeiro", "primo",
        "prisão", "privado", "problema", "processo", "procura",
        "produto", "professor", "profundo", "programa", "progresso",
        "proibir", "projeto", "pronto", "próprio", "proteger",
        "prova", "provar", "próximo", "prudente", "pudim",
        "pulga", "pulo", "pulmão", "pulso", "punhal",
        "punho", "puro", "puxar", "quadra", "quadrado",
        "quadro", "qual", "qualidade", "quando", "quanto",
        "quarta", "quarto", "quase", "quatro", "que",
        "quebra", "quebrar", "queda", "queijo", "queimar",
        "queixa", "queixo", "quem", "quente", "querer",
        "querido", "quieto", "quilómetro", "quilo", "química",
        "quina", "quinhão", "quinta", "quintal", "quinto",
        "quinze", "quitação", "quota", "raça", "ração",
        "raciocínio", "rasto", "radiação", "radical", "rádio",
        "raia", "rainha", "raio", "raiva", "raiz",
        "ralar", "ralo", "ramal", "ramo", "rampa",
        "rancho", "rápido", "raposa", "rarefação", "rasgar",
        "raso", "raspa", "raspar", "rascunho", "rato",
        "razão", "reagir", "real", "realidade", "realizar",
        "rebanho", "receber", "receio", "receita", "recente",
        "recheio", "recibo", "recinto", "recitar", "reclamar",
        "recolher", "recordar", "recorrer", "recuar", "recuperar",
        "recurso", "rede", "redondo", "reduzir", "refeição",
        "referência", "refinar", "refletir", "reforma", "refresco",
        "refúgio", "regalo", "regar", "região", "registo",
        "regra", "regressar", "régua", "rei", "reino",
        "reitor", "relação", "relógio", "relva", "remar",
        "remédio", "remeter", "remo", "renda", "render",
        "renovar", "reparar", "repousar", "representar", "reprovar",
        "reserva", "residir", "resistir", "resolver", "respeitar",
        "respirar", "responder", "resposta", "resto", "resultado",
        "retalho", "reter", "retirar", "retomar", "retorno",
        "retrato", "reunião", "reunir", "revelar", "revista",
        "rezar", "ria", "rico", "ridículo", "rifa",
        "rifle", "rigor", "rim", "rimar", "rio",
        "riqueza", "rir", "risada", "risco", "risonho",
        "ritmo", "rito", "rival", "rocha", "roda",
        "rodapé", "rodar", "rodela", "rodízio", "rodo",
        "roer", "rogado", "rogar", "rolo", "romance",
        "romano", "rombo", "romper", "roncar", "ronda",
        "rosto", "rota", "rotina", "rótulo", "roupa",
        "rouparia", "roubar", "roubo", "roxo", "rua",
        "rubi", "rude", "ruído", "ruína", "ruivo",
        "rumo", "rumor", "rutura", "sábado", "saber",
        "sabor", "sabre", "sacada", "saca", "saco",
        "sacola", "sacudir", "saúde", "safira", "sagrado",
        "saia", "saída", "sair", "sal", "sala",
        "salada", "salário", "saldo", "salgar", "salgado",
        "salinha", "salitre", "saliva", "salmão", "salmo",
        "saloio", "salsa", "saltar", "salto", "salvar",
        "samba", "sanar", "sandália", "sangue", "santo",
        "sapato", "saque", "sarar", "sardinha", "saudade",
        "seara", "seco", "secretaria", "sede", "seda",
        "segredo", "seguida", "seguinte", "seguir", "segunda",
        "segundo", "seguro", "seis", "sela", "selar",
        "selo", "selva", "sem", "semana", "semeador",
        "semente", "sempre", "senado", "sendo", "senha",
        "senhor", "senhora", "sentado", "sentença", "sentido",
        "sentir", "separar", "sereia", "série", "sério",
        "serpente", "serra", "serralheiro", "serrar", "serviço",
        "servir", "sessão", "seta", "setembro", "setenta",
        "setor", "seu", "severo", "sexta", "sexto",
        "si", "silêncio", "silo", "silva", "símbolo",
        "simples", "sinal", "sinceridade", "sincero", "sino",
        "sintoma", "sítio", "situação", "soar", "sob",
        "soberba", "sobra", "sobrar", "sobre", "sobremesa",
        "sobrinho", "sóbrio", "soca", "social", "sociedade",
        "soco", "socorro", "sofá", "sofrer", "sogra",
        "sogro", "sol", "solar", "solda", "soldado",
        "solteiro", "solto", "solução", "soma", "somar",
        "sombra", "sonhar", "sonho", "sono", "sopa",
        "soprar", "sopro", "soro", "sorrir", "sorriso",
        "sorte", "sorvete", "sossegado", "sossego", "sótão",
        "sou", "sozinho", "suave", "subida", "subir",
        "submarino", "subscrever", "subtil", "sucesso", "suco",
        "suécia", "suor", "sujar", "sujeira", "sujeito",
        "sujo", "sul", "sumo", "suor", "superar",
        "suporte", "supor", "surdo", "surgir", "surpresa",
        "susto", "suspeita", "taberna", "tábua", "taça",
        "tacho", "tal", "talento", "talha", "talher",
        "talho", "talvez", "tamanho", "também", "tambor",
        "tampa", "tangerina", "tanque", "tanto", "tão",
        "tapa", "tapar", "tapete", "tardada", "tarde",
        "tarefa", "tarifa", "tartaruga", "tasca", "tatuagem",
        "taverna", "taxa", "táxi", "teado", "teatro",
        "tecelão", "tecer", "tecido", "teclado", "técnico",
        "teto", "teia", "teimar", "teimoso", "tejo",
        "tela", "telefonar", "telefone", "telegrama", "televisão",
        "telha", "telhado", "tema", "temer", "temível",
        "temperança", "tempero", "tempestade", "templo", "tempo",
        "temporada", "tenaz", "tenda", "tenente", "ténis",
        "tenro", "tensão", "tentar", "teoria", "ter",
        "terça", "terceiro", "terço", "termómetro", "terno",
        "ternura", "terra", "terraço", "terreno", "terrível",
        "tesoura", "tesouro", "teste", "testemunha", "teto",
        "teu", "texto", "ti", "tia", "tigela",
        "tigre", "tijolo", "tília", "timoneiro", "tímpano",
        "tinta", "tinto", "tio", "tipo", "tiragem",
        "tirar", "tiro", "título", "toada", "toalha",
        "toca", "tocar", "tocha", "todavia", "todo",
        "toga", "toirar", "toiro", "tojo", "toldo",
        "tolerância", "tomada", "tomar", "tomate", "tombar",
        "tombo", "tom", "tonelada", "tonto", "topo",
        "toque", "tórax", "torcer", "tordo", "tormenta",
        "tornar", "torneio", "torno", "tornozelo", "torrada",
        "torrar", "torre", "torreira", "torrente", "torreão",
        "torta", "torto", "tortura", "tosquiar", "tosse",
        "tosser", "tostado", "total", "touca", "toucinho",
        "toupeira", "touro", "trabalho", "traço", "traição",
        "traje", "tramway", "trança", "tranquilo", "trânsito",
        "trapo", "trás", "tratado", "tratar", "travar",
        "trave", "travessa", "trazer", "trecho", "trégua",
        "treinar", "treino", "tremenda", "tremer", "tremoço",
        "tremura", "três", "trevas", "trevo", "treze",
        "tribo", "tribunal", "trigo", "trilho", "trimestre",
        "trinta", "tripa", "triplo", "triste", "tristeza",
        "triunfo", "troca", "trocar", "troço", "troféu",
        "tromba", "trompa", "tronco", "trono", "tropa",
        "tropeçar", "tropical", "trote", "trouxa", "trovão",
        "truque", "truta", "tu", "tua", "tubarão",
        "tubo", "tudo", "tufão", "túmulo", "túnel",
        "turba", "turismo", "turma", "turno", "turquesa",
        "tutela", "uivo", "último", "ultrapassar", "umbigo",
        "um", "unanimidade", "unha", "união", "único",
        "unidade", "unir", "universo", "um", "uns",
        "urbanidade", "urbano", "urbe", "urca", "urdir",
        "urgência", "urgente", "urina", "urinar", "urna",
        "urso", "urtiga", "urubu", "usado", "usar",
        "uso", "usura", "utensílio", "útero", "útil",
        "utilizar", "utopia", "uva", "vaca", "vacina",
        "vácuo", "vaga", "vagão", "vagar", "vago",
        "vaidade", "vaidoso", "vale", "valer", "valia",
        "validade", "valido", "valioso", "valura", "valvula",
        "vampiro", "vão", "vapor", "vara", "varanda",
        "varar", "varejo", "variante", "variar", "vário",
        "variz", "varrer", "vassoura", "vasto", "vazio",
        "veado", "vedar", "veia", "veículo", "vela",
        "veludo", "velhice", "velho", "velocidade", "veloz",
        "vencer", "venda", "venda", "vender", "veneno",
        "venerar", "venia", "venta", "ventar", "vento",
        "ventre", "ventura", "ver", "verão", "veras",
        "verba", "verbena", "verbo", "verdade", "verde",
        "vergonha", "verificar", "verme", "vermelho", "verna",
        "verniz", "verruga", "versão", "verso", "verter",
        "vértice", "vespa", "véspera", "vestibular", "vestido",
        "vestir", "veta", "vetar", "veterano", "veto",
        "vez", "via", "viagem", "viajar", "viandante",
        "viatura", "vibrar", "vício", "vida", "vidro",
        "viela", "viga", "vigiar", "vigor", "vila",
        "vilão", "vinagre", "vinco", "vinda", "vinfia",
        "vinte", "vinho", "viola", "violão", "violeta",
        "vir", "virar", "virgem", "vírgula", "virtude",
        "vírus", "visão", "visar", "visível", "visita",
        "visitar", "visor", "vista", "visto", "visual",
        "vital", "vítima", "vitória", "vitrina", "viúva",
        "viúvo", "viva", "viver", "vivido", "vivo",
        "vizinho", "voador", "voar", "vocal", "vocação",
        "você", "voga", "vontade", "voo", "vós",
        "votar", "voto", "voz", "vulgar", "vulgo",
        "vulto", "xadrez", "xale", "xampu", "xará",
        "xarope", "xeque", "xerife", "xícara", "xisto",
        "zanga", "zangar", "zanza", "zebra", "zelar",
        "zelo", "zero", "zinco", "zombar", "zona",
        "zumbir", "zurrar"
    ],
    "Game of Thrones": ["Westeros", "Essos", "Winterfell", "King's Landing", "Dragonstone", "The Wall", "Night's Watch",
        "Iron Throne", "Targaryen", "Stark", "Lannister", "Baratheon", "Greyjoy", "Martell", "Tyrell", "Arryn", "Tully",
        "Mormont", "Bolton", "Clegane", "Jon Snow", "Daenerys", "Tyrion", "Cersei", "Jaime", "Arya", "Sansa", "Bran",
        "Ned Stark", "Catelyn", "Robb", "Joffrey", "Stannis", "Renly", "Robert Baratheon", "Littlefinger", "Varys",
        "The Hound", "The Mountain", "Brienne of Tarth", "Tormund", "Ygritte", "Samwell Tarly", "Gendry",
        "Davos Seaworth", "Melisandre", "The Red Woman", "Khal Drogo", "Dothraki", "Valyrian", "Dracarys", "Drogon",
        "Rhaegal", "Viserion", "Direwolf", "Ghost", "Nymeria", "Summer", "Shaggydog", "Grey Wind", "Lady",
        "White Walker", "Night King", "Wight", "Dragonglass", "Valyrian Steel", "Wildfire", "Blackwater", "Red Wedding",
        "Purple Wedding", "The Long Night", "Winter is Coming", "Hear Me Roar", "Fire and Blood", "Ours is the Fury",
        "Family Duty Honor", "As High as Honor", "Unbowed Unbent Unbroken", "Growing Strong", "We Do Not Sow",
        "Kingslayer", "Khaleesi", "Hand of the King", "Small Council", "Maester", "Grand Maester", "Citadel", "Oldtown",
        "The Eyrie", "Pyke", "Riverrun", "Highgarden", "Dorne", "Sunspear", "Braavos", "Pentos", "Meereen", "Astapor",
        "Yunkai", "Volantis", "Qarth", "The Narrow Sea", "The Sunset Sea", "The Shivering Sea", "Black Castle",
        "Shadow Tower", "Eastwatch", "The Gift", "Mole's Town", "Craster's Keep", "Hardhome", "Fist of the First Men",
        "Wildlings", "Free Folk", "Mance Rayder", "Three-Eyed Raven", "Greensight", "Warg", "Old Gods",
        "Faith of the Seven", "The Father", "The Mother", "The Maiden", "The Crone", "The Warrior", "The Smith",
        "The Stranger", "R'hllor", "Lord of Light", "Drowned God", "Many-Faced God", "Valar Morghulis",
        "Valar Dohaeris", "Faceless Men", "Iron Bank", "Golden Company", "Second Sons", "Unsullied", "Grey Worm",
        "Missandei", "Jorah Mormont", "Lyanna Mormont", "Jeor Mormont", "Benjen Stark", "Rickon Stark", "Hodor",
        "Meera Reed", "Jojen Reed", "Howland Reed", "Arthur Dayne", "Sword of the Morning", "Dawn", "Longclaw",
        "Needle", "Ice", "Oathkeeper", "Widow's Wail", "Heartsbane", "Blackfyre", "Dark Sister", "Lightbringer",
        "Aegon the Conqueror", "Visenya", "Rhaenys", "Mad King", "Aerys II", "Rhaegar", "Lyanna Stark", "Tower of Joy",
        "Trident", "The Twins", "Walder Frey", "Roose Bolton", "Ramsay Bolton", "Reek", "Theon Greyjoy", "Yara Greyjoy",
        "Euron Greyjoy", "Balon Greyjoy", "Victarion", "Aeron Damphair", "Sand Snakes", "Ellaria Sand",
        "Oberyn Martell", "Doran Martell", "High Sparrow", "Sept of Baelor", "Great Sept", "Fleabottom", "Red Keep",
        "Maegor's Holdfast", "The Black Cells", "The Moon Door", "Sky Cells", "Bloody Gate", "Gates of the Moon",
        "The Fingers", "Bear Island", "Dreadfort", "Moat Cailin", "The Neck", "Greywater Watch", "Harrenhal",
        "Gods Eye", "Isle of Faces", "Dragonpit", "Street of Sisters", "Street of Steel", "Muddy Way", "Kingswood",
        "Rainwood", "Storm's End", "Shipbreaker Bay", "Tarth", "Stepstones", "Disputed Lands", "Red Waste",
        "Vaas Dothrak", "House of the Undying", "Warlocks", "Pyat Pree", "Slaver's Bay", "Bay of Dragons",
        "Great Pyramid", "Fighting Pits", "Daznak's Pit", "Harpy", "Sons of the Harpy", "Stone Men", "Valyria",
        "Doom of Valyria", "Smoking Sea", "Ghiscar", "Asshai", "Shadow Lands", "Yi Ti", "Leng", "Ibben", "Skagos",
        "Giant", "Mammoth", "Children of the Forest", "First Men", "Andals", "Rhoynar", "Nymeria's Ten Thousand Ships",
        "War of the Five Kings", "Dance of the Dragons", "Blackfyre Rebellion", "Robert's Rebellion",
        "Tourney at Harrenhal", "Greyjoy Rebellion", "Kingsguard", "Queensguard", "Gold Cloaks", "City Watch",
        "Lord Commander", "First Ranger", "First Builder", "First Steward", "Maester Aemon", "Grand Maester Pycelle",
        "Qyburn", "Gregor Clegane", "Sandor Clegane", "Beric Dondarrion", "Thoros of Myr",
        "Brotherhood Without Banners", "Anguy", "Lemoncloak", "Gilly", "Baby Sam", "Lord of Bones", "Rattleshirt",
        "Orell", "Styr", "Magnar of Thenn", "Thenns", "Karsi", "Leaf", "Bloodraven", "Weirwood", "Heart Tree",
        "Godswood", "Raven", "Crow", "Milk of the Poppy", "Moon Tea", "Essence of Nightshade", "Lizard-lion", "Kraken",
        "Manticore", "Shadowcat", "Arakh", "Warhammer", "Morningstar", "Crossbow", "Scorpion", "Wildling raiding",
        "Trial by Combat", "Trial by Seven", "Right of First Night", "Squire", "Knight", "Ser", "My Lord", "Your Grace",
        "Smallfolk", "Bastard", "Snow", "Stone", "Rivers", "Hill", "Pyke", "Flowers", "Storm", "Waters", "Sand",
        "Summer Isles", "Golden Heart", "Iron Islands", "The Reach", "The Riverlands", "The Westerlands",
        "The Stormlands", "The Crownlands", "The Vale", "The North", "Sea of Dorne", "Summer Sea", "Jade Sea",
        "Bravosian Blade", "Water Dancer", "Syrio Forel", "Jaquen H'ghar", "The Waif", "Hall of Faces",
        "Black and White", "Titan of Braavos", "Iron Price", "Gold Price", "Salt Wife", "Rock Wife", "Driftwood Throne",
        "Seastone Chair", "Kingsmoot", "Dreadfort Flaying", "Pink Letter", "Bastard of Bolton",
        "Knight of the Laughing Tree", "Azor Ahai", "Prince That Was Promised", "Nissa Nissa", "Horn of Winter",
        "Dragonbinder", "Hellhorn", "Wildfire Alchemists", "Pyromancers", "The Alchemists' Guild", "Brother Lancel",
        "Lancel Lannister", "Kevan Lannister", "Alton Lannister", "Martyn Lannister", "Willem Lannister",
        "Podrick Payne", "Ilyn Payne", "King's Justice", "The Silent Sisters", "Bows", "Spears", "Shields", "Phalanx",
        "Siege", "Catapult", "Trebuchet", "Ram", "Ladder", "Oil", "Pitch", "Arrow", "Bolt", "Dagger", "Dirk",
        "Shortsword", "Greatsword", "Bastard Sword", "Longsword", "Mace", "Flail", "Axe", "Shield", "Plate", "Mail",
        "Leather", "Gambeson", "Helm", "Gorget", "Pauldron", "Vambrace", "Gauntlet", "Greave", "Sabaton", "Visor",
        "Surcoat", "Sigil", "Banner", "Standard", "Standard Bearer", "Heraldry", "Coat of Arms", "Lord Paramount",
        "Warden of the North", "Warden of the East", "Warden of the West", "Warden of the South",
        "Protector of the Realm", "King of the Andals", "First of His Name", "Breaker of Chains", "Mother of Dragons",
        "The Unburnt", "Silver Lady", "Khal", "Bloodrider", "Ko", "Kalasar", "Aemon Targaryen", "Aerion Brightflame",
        "Baelor Breakspear", "Daemon Blackfyre", "Bittersteel", "Bloodraven", "Shiera Seastar", "The Hedge Knight",
        "Dunk and Egg", "Ser Duncan the Tall", "Summerhall", "Tragedy at Summerhall", "Ghost of High Heart",
        "The Rat Cook", "The Night's King", "Lann the Clever", "Brandon the Builder", "Garth Greenhand",
        "Durran Godsgrief", "Grey King", "Symeon Star-Eyes", "Florian the Fool", "Jonquil", "Ser Pounce",
        "Balerion the Black Dread", "Meraxes", "Vhagar", "Sunfyre", "Syrax", "Caraxes", "Meleys", "Vermax",
        "Arrax", "Tyraxes", "Stormcloud", "Tessarion", "Seasmoke", "Sheepstealer", "Cannibal", "Grey Ghost",
        "Morning", "Shrykos", "Morghul", "Dreamfyre", "Moondancer", "Silverwing", "Vermithor", "The Last Hearth",
        "Karhold", "White Harbor", "Greyguard", "Sentinel Stand", "Hoarfrost Hill", "Icemark", "The Nightfort",
        "Deep Lake", "Queensgate", "Oakenshield", "Woodswatch-by-the-Pool", "Sable Hall", "Rimegate", "The Tor",
        "The Arbor", "Old Oak", "Goldengrove", "Casterly Rock", "Lannisport", "Castamere", "Tarbeck Hall",
        "The Golden Tooth", "Ashemark", "Cravenhall", "Cornfield", "Banefort", "Crag", "Sarsfield", "Feastfires",
        "Hornvale", "Deep Den", "Silverhall", "Oxcross", "Wyll", "Yronwood", "Starfall", "Hellholt", "Salt Shore",
        "Blackmont", "High Hermitage", "Kingsgrave", "Ghost Hill", "Godsgrace", "The Lemonwood", "Planky Town", "Vaith",
    ],
    "Harry Potter": [
        "Harry Potter", "Hermione Granger", "Ron Weasley", "Albus Dumbledore", "Lord Voldemort", "Severus Snape",
        "Rubeus Hagrid", "Draco Malfoy", "Sirius Black", "Remus Lupin", "Minerva McGonagall", "Neville Longbottom",
        "Luna Lovegood", "Ginny Weasley", "Fred Weasley", "George Weasley", "Molly Weasley", "Arthur Weasley",
        "Bellatrix Lestrange", "Lucius Malfoy", "Narcissa Malfoy", "Dolores Umbridge", "Alastor Moody",
        "Kingsley Shacklebolt", "Nymphadora Tonks", "Cedric Diggory", "Cho Chang", "Fleur Delacour", "Viktor Krum",
        "Dudley Dursley", "Petunia Dursley", "Vernon Dursley", "Lily Potter", "James Potter", "Tom Riddle",
        "Peter Pettigrew", "Gilderoy Lockhart", "Sybill Trelawney", "Horace Slughorn", "Quirinus Quirrell",
        "Argus Filch", "Mrs. Norris", "Hedwig", "Scabbers", "Crookshanks", "Pigwidgeon", "Fang", "Aragog", "Buckbeak",
        "Fluffy", "Norbert", "Fawkes", "Dobby", "Kreacher", "Winky", "Griphook", "Bogrod", "Grawp", "Hogwarts",
        "Gryffindor", "Slytherin", "Ravenclaw", "Hufflepuff", "Great Hall", "Forbidden Forest", "Quidditch Pitch",
        "Common Room", "Astronomy Tower", "Hagrid's Hut", "Whomping Willow", "Black Lake", "Room of Requirement",
        "Chamber of Secrets", "Diagon Alley", "Knockturn Alley", "The Leaky Cauldron", "Gringotts", "Ollivanders",
        "Flourish and Blotts", "Weasleys' Wizard Wheezes", "Madam Malkin's", "Eeylops Owl Emporium",
        "Quality Quidditch Supplies", "Borgin and Burkes", "Hogsmeade", "The Three Broomsticks", "The Hog's Head",
        "Honeydukes", "Zonko's", "Shrieking Shack", "The Burrow", "Godric's Hollow", "Little Whinging", "Privet Drive",
        "Grimmauld Place", "Malfoy Manor", "Shell Cottage", "Ministry of Magic", "St. Mungo's", "Azkaban", "Nurmengard",
        "Beauxbatons", "Durmstrang", "Ilvermorny", "Platform 9 3/4", "Hogwarts Express", "Knight Bus", "Portkey",
        "Floo Powder", "Apparition", "The Veil", "The Pensieve", "Mirror of Erised", "Sorcerer's Stone",
        "Philosopher's Stone", "Invisibility Cloak", "Elder Wand", "Resurrection Stone", "Deathly Hallows",
        "Horcrux", "Tom Riddle's Diary", "Marvolo Gaunt's Ring", "Slytherin's Locket", "Hufflepuff's Cup",
        "Ravenclaw's Diadem", "Nagini", "Marauder's Map", "Sneakoscope", "Remembrall", "Time-Turner", "Deluminator",
        "Pensieve", "Goblet of Fire", "Triwizard Cup", "Sword of Gryffindor", "Sorting Hat", "Expecto Patronum",
        "Expelliarmus", "Avada Kedavra", "Crucio", "Imperio", "Wingardium Leviosa", "Alohomora", "Lumos", "Nox",
        "Accio", "Stupefy", "Petrificus Totalus", "Sectumsempra", "Riddikulus", "Protego", "Expecto Patronum",
        "Obliviate", "Confundo", "Diffindo", "Aguamenti", "Incendio", "Revelio", "Engorgio", "Reducto", "Bombarda",
        "Legilimens", "Occlumency", "Muggle", "Squib", "Mudblood", "Pure-blood", "Half-blood", "Animagus",
        "Metamorphmagus", "Parselmouth", "Parseltongue", "Legilimens", "Auror", "Unspeakable", "Death Eater",
        "Order of the Phoenix", "Dumbledore's Army", "Inquisitorial Squad", "Ministry of Magic", "Daily Prophet",
        "The Quibbler", "Wizengamot", "International Statue of Secrecy", "Quidditch", "Golden Snitch", "Bludger",
        "Quaffle", "Beater", "Chaser", "Keeper", "Seeker", "Firebolt", "Nimbus 2000", "Nimbus 2001", "Cleansweep Seven",
        "Shooting Star", "Wandering with Werewolves", "Hogwarts: A History", "The Tales of Beedle the Bard",
        "Fantastic Beasts and Where to Find Them", "Quidditch Through the Ages", "Butterbeer", "Firewhisky",
        "Pumpkin Juice", "Chocolate Frogs", "Bertie Bott's Every Flavor Beans", "Sugar Quills", "Acid Pops",
        "Drooble's Best Blowing Gum", "Cauldron Cakes", "Licorice Wands", "Exploding Bonbons", "Polyjuice Potion",
        "Veritaserum", "Felix Felicis", "Amortentia", "Draught of Living Death", "Wolfsbane Potion", "Skele-Gro",
        "Essence of Dittany", "Bezoar", "Mandrake", "Devil's Snare", "Gillyweed", "Bubotuber Pus", "Whomping Willow",
        "Boggart", "Dementor", "Thestral", "Centaur", "House-elf", "Goblin", "Giant", "Werewolf", "Vampire",
        "Merpeople", "Grindylow", "Kappa", "Cornish Pixie", "Blast-Ended Skrewt", "Flooberworm", "Bowtruckle",
        "Niffler", "Hippogriff", "Phoenix", "Basilisk", "Hungarian Horntail", "Norwegian Ridgeback", "Chinese Fireball",
        "Swedish Short-Snout", "Common Welsh Green", "Ukrainian Ironbelly", "Acromantula", "Sphinx", "Manticore",
        "Chimera", "Blast-Ended Skrewt", "Skrewt", "Occamy", "Thunderbird", "Demiguise", "Erumpent", "Billywig",
        "Mooncalf", "The Grim", "Headless Hunt", "Nearly Headless Nick", "The Grey Lady", "The Bloody Baron",
        "The Fat Friar", "Moaning Myrtle", "Peeves", "Professor Binns", "Fat Lady", "Sir Cadogan",
        "Phineas Nigellus Black", "Walburga Black", "Regulus Black", "Andromeda Tonks", "Ted Tonks",
        "Victoire Weasley", "Teddy Lupin", "James Sirius Potter", "Albus Severus Potter", "Lily Luna Potter",
        "Rose Granger-Weasley", "Hugo Granger-Weasley", "Scorpius Malfoy", "Astoria Greengrass", "Pansy Parkinson",
        "Blaise Zabini", "Theodore Nott", "Millicent Bulstrode", "Gregory Goyle", "Vincent Crabbe", "Marcus Flint",
        "Oliver Wood", "Angelina Johnson", "Alicia Spinnet", "Katie Bell", "Lee Jordan", "Dean Thomas",
        "Seamus Finnigan", "Lavender Brown", "Parvati Patil", "Padma Patil", "Terry Boot", "Michael Corner",
        "Anthony Goldstein", "Justin Finch-Fletchley", "Ernie Macmillan", "Hannah Abbott", "Susan Bones",
        "Zacharias Smith", "Cormac McLaggen", "Romilda Vane", "Stan Shunpike", "Ernie Prang", "Rita Skeeter",
        "Ludo Bagman", "Bartemius Crouch Sr.", "Bartemius Crouch Jr.", "Igor Karkaroff", "Madam Maxime",
        "Gabrielle Delacour", "Abernathy", "Seraphina Picquery", "Newt Scamander", "Tina Goldstein",
        "Queenie Goldstein", "Jacob Kowalski", "Credence Barebone", "Gellert Grindelwald", "Percival Graves",
        "Leta Lestrange", "Theseus Scamander", "Niffler", "Pickett", "Frank the Thunderbird", "Zouwu", "Kelpie",
        "Matagot", "Naginas", "Dark Mark", "Howler", "Owl Post", "Squib", "Prefect", "Head Boy", "Head Girl",
        "Quidditch Captain", "O.W.L.s", "N.E.W.T.s", "Grim", "The Tale of the Three Brothers", "Wand Wood",
        "Dragon Heartstring", "Phoenix Feather", "Unicorn Hair", "Veela Hair", "Thestral Tail Hair", "Thirteen Inches",
        "Holly", "Yew", "Oak", "Vine", "Willow", "Hawthorn", "Elder", "Maple", "Mahogany", "Ash", "Cedar", "Cherry",
        "Fir", "Walnut", "Blackthorn", "Rosewood", "Hornbeam", "Ebony", "Birch", "Kneazle", "Puffskein", "Pygmy Puff",
        "Flobberworm", "Salamander", "Fire Crab", "Doxy", "Red Cap", "Hinkypunk", "Binkky", "Winky", "Hooky", "Mipsy",
        "Pluckey", "Galleon", "Sickle", "Knut", "Pensieve", "Omnioculars", "Muffliato", "Levicorpus", "Liberacorpus",
        "Anapneo", "Episkey", "Tergeo", "Specialis Revelio", "Silencio", "Aguamenti", "Geminio", "Flagrate",
        "Homenum Revelio", "Meteolojinx Recanto", "Salvio Hexia", "Protego Totalum", "Repello Muggletum",
        "Muggle-Worthy", "Confundus Charm", "Feather-light Charm", "Permanent Sticking Charm",
        "Undetectable Extension Charm", "Taboo", "Broken Promise", "Blood Pact", "Unbreakable Vow", "Pensieve",
        "Memories", "Wizengamot", "Aura", "Magical Core", "Wandlore", "The Boy Who Lived", "The Chosen One",
        "He-Who-Must-Not-Be-Named", "You-Know-Who", "The Dark Lord", "Prongs", "Padfoot", "Moony", "Wormtail",
        "Gillyweed", "Shrinking Potion", "Wit-Sharpening Potion", "Forgetfulness Potion", "Herbology", "Potions",
        "Transfiguration", "Charms", "Defense Against the Dark Arts", "Divination", "Arithmancy", "Ancient Runes",
        "Care of Magical Creatures", "Muggle Studies", "History of Magic", "Apparition Lessons", "Flying Lessons",
        "Duelling Club", "Slug Club", "S.P.E.W.", "Gringotts Curse-Breaker", "Dragonologist", "Healer",
        "Magizoologist", "Squib", "Obscurial", "Obscurus", "Blood Malediction", "Maledictus"
    ],
    "Scy-Fy": [
        "Andromeda", "Android", "Annihilation", "Antimatter", "Apocalypse", "Artificial Intelligence", "Asteroid Belt", "Astrobiology", "Astronaut", "Atmosphere", "Augmentation", "Autonomous", "Avatar", "Babel Fish", "Beam", "Binary System", "Biohacking", "Bionic", "Biosphere", "Black Hole", "Blast-off", "Blaster", "Borg", "Bounty Hunter", "Brain-Computer Interface", "Cabal", "Capsule", "Carbon-Based", "Celestial", "Centauri", "Chrome", "Chronicle", "Cyborg", "Cryonics", "Cryosleep", "Cybernetic", "Cyberpunk", "Cyberspace", "Dark Matter", "Data", "Deep Space", "Deuterium", "Dimension", "Droid", "Dune", "Dystopia", "Eclipitic", "Ecology", "Exoplanet", "Extraterrestrial", "Event Horizon", "Evolution", "Exoskeleton", "Faster Than Light", "Federation", "Fermi Paradox", "Force Field", "Fusion", "Galactic", "Galaxy", "Gamma Ray", "Genetic Engineering", "Geostationary", "Gravity", "Great Filter", "Habitable Zone", "Hacking", "Hologram", "Hostile", "Humanoid", "Hyperdrive", "Hyperspace", "Ice Giant", "Implants", "Intergalactic", "Interstellar", "Ion Drive", "Jovian", "Jupiter", "Kardashev Scale", "Kinetic Energy", "Klingon", "Laser", "Launchpad", "Lightyear", "Life-Support", "Lunar", "Machine Learning", "Mainframe", "Mars", "Martian", "Matter", "Mecha", "Mega-structure", "Memory Wipe", "Metropolis", "Microchip", "Milky Way", "Modem", "Moon", "Multiverse", "Mutant", "Nanobots", "Nanotechnology", "Nebula", "Neural Link", "Neutron Star", "New World", "Nova", "Nuclear", "Orbit", "Orbital", "Outpost", "Oxygen", "Parallel Universe", "Parsec", "Particle", "Photon", "Plasma", "Planet", "Planetary", "Post-Apocalyptic", "Post-Human", "Processor", "Program", "Propulsion", "Protostellar", "Pulsar", "Quantum", "Quasar", "Radiation", "Radio", "Replicant", "Robot", "Robotics", "Rocket", "Rover", "Satellite", "Saturn", "Scanner", "Scavenger", "Sci-Fi", "Scout", "Sector", "Sentinel", "Ship", "Shuttle", "Singularity", "Skyline", "Solar", "Solar Sail", "Space", "Spacecraft", "Spacesuit", "Space-time", "Species", "Speculation", "Star", "Starship", "Starbase", "Stellar", "Supernova", "Surveillance", "Synthetic", "System", "Technology", "Telekinesis", "Telepathy", "Teleportation", "Terraform", "Terran", "Thermal", "Timeline", "Titan", "Tractor Beam", "Trajectory", "Transhumanism", "Transmitter", "Transporter", "Trek", "Turing Test", "UFO", "Universe", "Utopia", "Vacuum", "Valiant", "Vault", "Vessel", "Virtual Reality", "Virus", "Void", "Volcanic", "Vortex", "Warp Drive", "Wavelength", "Weaponry", "Wormhole", "Xenobiology", "Xenomorph", "Zero Gravity", "Zion", "Zone", "Arrakis", "Spice", "Stillsuit", "Kwisatz Haderach", "Guild Navigator", "Tatooine", "Jedi", "Sith", "Lightsaber", "Millennium Falcon", "Death Star", "Padawan", "Vulcan", "Enterprise", "Holodeck", "Phaser", "Prime Directive", "Tardis", "Dalek", "Time Lord", "Gallifrey", "Cyberman", "Skynet", "Terminator", "The Matrix", "Nebuchadnezzar", "Sentinel", "Deckard", "Tyrell Corporation", "Voight-Kampff", "Spinner", "Vader", "Skywalker", "Kenobi", "Coruscant", "Hoth", "Endor", "Naboo", "Alderaan", "Geonosis", "Kamino", "Dagobah", "Bespin", "Mustafar", "X-Wing", "TIE Fighter", "Deathwing", "Star Destroyer", "Ewok", "Wookiee", "R2-D2", "C-3PO", "Grogu", "Mandalorian", "Beskar", "Spock", "Kirk", "Picard", "Data", "Seven of Nine", "Riker", "Worf", "Borg Cube", "Voyager", "Deep Space Nine", "Klingon", "Romulan", "Ferengi", "Cardassian", "Dominion", "Tribble", "Dilithium", "Plasma Conduit", "Isolinear Chip", "Nerve Pinch", "Live Long and Prosper", "Engage", "Make it So", "Resistance is Futile", "Paul Atreides", "Leto", "Jessica", "Chani", "Stilgar", "Baron Harkonnen", "Feyd-Rautha", "Shai-Hulud", "Sandworm", "Bene Gesserit", "Mentat", "Sardaukar", "Caladan", "Giedi Prime", "Ix", "Spacing Guild", "Ornithopter", "Gom Jabbar", "Butlerian Jihad", "Spice Melange", "The Sleeper Must Awaken", "Fear is the Little-Death", "Case", "Molly Millions", "Wintermute", "Neuromancer", "Turing Police", "Night City", "The Sprawl", "Deck", "Console Cowboy", "Simstim", "Netrunner", "Icebreaker", "Black Ice", "Hiro Protagonist", "Snow Crash", "Metaverse", "Gargoyle", "Rat Thing", "Avatars", "Enlil", "Lagos", "Foundation", "Hari Seldon", "Psychohistory", "Trantor", "The Mule", "Terminus", "The Cleon", "Empire", "Solaris", "Kelvin", "Ocean", "Mimic", "Lem", "Asimov", "Three Laws", "Arthur C. Clarke", "Monolith", "HAL 9000", "Discovery One", "Jupiter Mission", "Stargate", "Abydos", "Chappa'ai", "Goa'uld", "Jaffa", "Teal'c", "O'Neill", "ZPM", "Wraith", "Asgard", "Replicators", "Serenity", "Firefly", "Mal Reynolds", "Wash", "Zoe", "Kaylee", "Jayne", "River Tam", "Simon", "Inara", "Book", "Reavers", "Alliance", "Browncoats", "Shiny", "Gorram", "Expanse", "Rocinante", "Holden", "Naomi", "Amos", "Alex", "Miller", "Julie Mao", "Protogen", "Protomolecule", "Ring Gate", "The Belt", "Belter", "OPA", "UN", "MCRN", "Phoebe", "Eros", "Tycho Station", "Ceres", "Ganymede", "Iapetus", "Gravity Well", "Epstein Drive", "PDC", "Railgun", "Mag Boot", "Tightbeam", "Vac-suit", "Red Dwarf", "Lister", "Rimmer", "Cat", "Kryten", "Holly", "Starbug", "Smeghead", "Babylon 5", "Sheridan", "Delenn", "G'Kar", "Londo", "Shadows", "Vorlons", "Whitestar", "Minbari", "Narn", "Centauri", "Battlestar Galactica", "Adama", "Starbuck", "Apollo", "Roslin", "Cylon", "Centurion", "Basestar", "Viper", "Raptor", "Fracking", "So Say We All", "Twelve Colonies", "Kobol", "Earth", "Final Five", "Gaeta", "Tigh", "Baltar", "Six", "Starship Troopers", "Rico", "Roughnecks", "Brain Bug", "Klendathu", "Power Armor", "Citizenship", "Service", "Total Recall", "Mars", "Memory Implant", "Kuato", "Quade", "Benny", "Three-armed", "Fifth Element", "Leeloo", "Korben Dallas", "Multipass", "Zorg", "Mandalore", "Ruby Rhod", "Mondoshawan", "Diva Plavalaguna", "Aliens", "Ripley", "Newt", "Hicks", "Hudson", "Bishop", "Xenomorph", "Facehugger", "Chestburster", "Queen", "Weyland-Yutani", "Nostromo", "Sulaco", "LV-426", "Power Loader", "Pulse Rifle", "Predator", "Dutch", "Yautja", "Cloak", "Wristblade", "Plasma Caster", "Thermal Vision", "Dillon", "The Jungle", "Chopper", "Robocop", "Murphy", "OCP", "ED-209", "Delta City", "Detroit", "Directive", "Prime Directive", "Flash Gordon", "Ming the Merciless", "Mongo", "Vultan", "Hawkmen", "Zarkov", "Dale", "Rocket Cycle", "War of the Worlds", "Heat-Ray", "Tripod", "Martian Cylinder", "H.G. Wells", "Invasion", "Brave New World", "Soma", "Alpha", "Beta", "Gamma", "Delta", "Epsilon", "Hatchery", "World State", "Lenina", "Bernard", "1984", "Big Brother", "Oceania", "Newspeak", "Thoughtcrime", "Doublethink", "Telescreen", "Room 101", "Winston Smith", "Julia", "O'Brien", "The Party", "Inception", "Cob", "Arthur", "Eames", "Ariadne", "Saito", "Mal", "Limbo", "Kick", "Totem", "Dream Sharing", "PASIV Device", "The Prestige", "Angier", "Borden", "Tesla", "Machine", "Duplicate", "Clone", "Prestige", "Turn", "Pledge", "Elysium", "Orbital Station", "Med-Pod", "Spider", "Max Da Costa", "Kruger", "Armadyne", "District 9", "Wikus", "Christopher Johnson", "Prawn", "Johannesburg", "Fluid", "Exosuit", "Arrival", "Louise Banks", "Ian Donnelly", "Heptapod", "Abbott", "Costello", "Logogram", "Non-linear", "Twelve", "Interstellar", "Cooper", "Murph", "Brand", "TARS", "CASE", "Endurance", "Gargantua", "Miller's Planet", "Mann's Planet", "Tesseract", "Gravity Data", "Contact", "Ellie Arroway", "Palmer Joss", "Hadden", "Vega", "Signal", "Machine", "Wormhole Trip", "The Martian", "Mark Watney", "Hermes", "Pathfinder", "Sojourner", "Sol", "Hab", "Potato", "Iron Man", "Stark", "Jarvis", "Arc Reactor", "Nanotech", "Ultron", "Vision", "Thanos", "Infinity Stone", "Glove", "Snapshot", "Blip", "Avatar", "Jake Sully", "Neytiri", "Pandora", "Na'vi", "Unobtainium", "Eywa", "Banshee", "Toruk", "Quaritch", "Selfridge", "Ender's Game", "Andrew Wiggin", "Valentine", "Peter", "Graff", "Mazer Rackham", "Buggers", "Formics", "Battle Room", "Ansible", "Dr. Who", "Sonic Screwdriver", "Regeneration", "Exterminate", "The Master", "River Song", "Amy Pond", "Rory Williams", "Clara Oswald", "Rose Tyler", "David Tennant", "Matt Smith", "Tom Baker", "Jodie Whittaker", "Christopher Eccleston"
    ],
    "Lord of the Rings": [
        "Frodo Baggins", "Samwise Gamgee", "Gandalf", "Aragorn", "Legolas", "Gimli", "Boromir", "Meriadoc Brandybuck", "Peregrin Took", "Gollum", "Smeagol", "Sauron", "Saruman", "Galadriel", "Elrond", "Arwen", "Theoden", "Eowyn", "Eomer", "Faramir", "Denethor", "Bilbo Baggins", "The Witch-king", "Nazgul", "Ringwraiths", "Mouth of Sauron", "Grima Wormtongue", "Radagast", "Glorfindel", "Haldir", "Celeborn", "Cirdan", "Isildur", "Elendil", "Gil-galad", "Bereth", "Luthien", "Beren", "Tuor", "Idril", "Earendil", "Morgoth", "Melkor", "Ungoliant", "Shelob", "Balrog", "Durin's Bane", "Glaurung", "Ancalagon", "Smaug", "Treebeard", "Quickbeam", "Tom Bombadil", "Goldberry", "Barliman Butterbur", "Gwaihir", "Shadowfax", "Bill the Pony", "One Ring", "Ruling Ring", "Narya", "Nenya", "Vilya", "Palantir", "Silmaril", "Evenstar", "Phial of Galadriel", "Anduril", "Narsil", "Sting", "Glamdring", "Orcrist", "Aeglos", "Gurthang", "Grond", "Herugrim", "Mithril", "Lembas", "Miruvor", "Orc-draught", "Middle-earth", "The Shire", "Hobbiton", "Bag End", "Buckland", "Bree", "Prancing Pony", "Weathertop", "Rivendell", "Imladris", "Misty Mountains", "Moria", "Khazad-dum", "Bridge of Khazad-dum", "Lothlorien", "Caras Galadhon", "Anduin", "Argonath", "Rauros", "Amon Hen", "Dead Marshes", "Emyn Muil", "Isengard", "Orthanc", "Fangorn Forest", "Rohan", "Edoras", "Meduseld", "Helm's Deep", "Hornburg", "Gondor", "Minas Tirith", "Osgiliath", "Minas Morgul", "Cirith Ungol", "Mordor", "Mount Doom", "Orodruin", "Barad-dur", "Black Gate", "Morannon", "Ithilien", "Dol Guldur", "Mirkwood", "Erebor", "Lonely Mountain", "Dale", "Esgaroth", "Lake-town", "Grey Havens", "Mithlond", "Numenor", "Valinor", "Undying Lands", "Beleriand", "Angband", "Utumno", "Eriador", "Dunland", "Enedwaith", "Harad", "Umbar", "Khand", "Rhun", "Blue Mountains", "Ered Luin", "Iron Hills", "Hobbit", "Halfling", "Man", "Elf", "Dwarf", "Orc", "Uruk-hai", "Goblin", "Troll", "Olog-hai", "Ent", "Eagle", "Warg", "Spider", "Skin-changer", "Beorn", "Istari", "Wizard", "Maiar", "Valar", "Eru Iluvatar", "Ainur", "Periannath", "Quenya", "Sindarin", "Khuzdul", "Black Speech", "Adunaic", "Westron", "Tengwar", "Cirth", "Eldar", "Noldor", "Sindar", "Teleri", "Vanyar", "Avari", "Naugrim", "Atani", "Dunadan", "Rangers", "Dunedain", "Haradrim", "Easterlings", "Corsairs", "Rohirrim", "Eorlingas", "Wainriders", "Variags", "Orc-host", "Mumakil", "Oliphaunt", "Beacons of Gondor", "White Tree", "Nimloth", "Simbelmyne", "Mallorn", "Athelas", "Kingsfoil", "Pipe-weed", "Longbottom Leaf", "Old Toby", "Southern Star", "Elevenses", "Luncheon", "Second Breakfast", "Mathom", "Party Tree", "Green Dragon", "Brandywine", "Greyflood", "Baranduin", "Gwathlo", "Bruinen", "Loudwater", "Silverlode", "Celebrant", "Entwash", "Gladden Fields", "Dimrill Dale", "Azanulbizar", "Khazad-ai-menu", "Baruk Khazad", "Mellon", "Elen sila lumenn omentielvo", "Ash Nazg Durbatuluk", "Namarié", "Hannon le", "Mae govannen", "Aiya", "Elessar", "Strider", "Dunhere", "Thengel", "Fenghel", "Helm Hammerhand", "Aldor", "Fréaláf", "Eorl the Young", "Battle of Unnumbered Tears", "Dagor Bragollach", "Battle of Sudden Flame", "Dagor-nuin-Giliath", "Dagor Aglareb", "War of the Last Alliance", "Battle of the Five Armies", "Battle of the Peak", "Battle of the Fords of Isen", "Battle of the Hornburg", "Battle of Pelennor Fields", "Battle of the Black Gate", "Scouring of the Shire", "Battle of Bywater", "Long Winter", "Fell Winter", "Great Plague", "Kin-strife", "Watcher in the Water", "The Great Eye", "Lidless Eye", "Dark Lord", "Necromancer", "White Wizard", "Grey Pilgrim", "Mithrandir", "Stormcrow", "Tharkun", "Incanus", "Lathspell", "Sharkey", "Estel", "Thorongil", "Winged Messenger", "Gorgoroth", "Udun", "Nurn", "Lithlad", "Plateau of Gorgoroth", "Durin's Tower", "Endless Stair", "Chamber of Mazarbul", "Book of Mazarbul", "Balin's Tomb", "Dwarrowdelf", "West-gate", "East-gate", "Redhorn", "Caradhras", "Celebdil", "Fanuidhol", "Gap of Rohan", "Fords of Isen", "Wold", "Eastemnet", "Westemnet", "Folde", "Fenmarch", "Starkhorn", "Dwimorberg", "Paths of the Dead", "Oathbreakers", "Stone of Erech", "Lossarnach", "Lebennin", "Belfalas", "Anfalas", "Pelargir", "Dol Amroth", "Swan Knights", "Prince Imrahil", "Rammas Echor", "Pelennor", "Rath Dinoel", "Houses of Healing", "Tower of Ecthelion", "White Tower", "Steward of Gondor", "King of the West", "Return of the King", "Fellowship", "The Two Towers", "Journey's End", "Fourth Age", "Second Age", "First Age", "Years of the Trees", "Years of the Lamps", "Music of the Ainur", "Great Music", "Void", "Timeless Halls", "World That Is", "Arda", "Middle-earth", "Outer Sea", "Ekkaia", "Helcaraxe", "Taniquetil", "Oiolosse", "Halls of Mandos", "Gardens of Lorien", "Ezellohar", "Two Trees of Valinor", "Telperion", "Laurelin", "Moon", "Sun", "Isil", "Anar", "Morning Star", "Evening Star", "Sickle of the Valar", "Valacirca", "Door of Night", "Straight Road", "Lost Road", "World Made Round", "Akallabeth", "Downfall of Numenor", "Land of Gift", "Andor", "Elenna", "Star of Earendil", "Sceptre of Annuminas", "Ring of Barahir", "Elessar Stone", "Elfstone", "White Staff", "Red Book of Westmarch", "Thain's Book", "Tale of Years", "There and Back Again", "The Hobbit", "Dragon-fire", "Mortal Men", "Doom of Men", "Gift of Men", "Immortality", "Fading", "Shadow World", "Unseen", "Wraith-world", "Morgul-blade", "Morgul-wound", "Black Breath", "Black Shadow", "Uruk", "Snaga", "Warg-rider", "Half-orc", "Goblin-men", "Man-orc", "Oliphaunt-rider", "Harad-road", "Southrons", "Easterlings", "Swarthy Men", "Dunlendings", "Wild Men of the Woods", "Woses", "Ghan-buri-Ghan", "Druedain", "Drúwaith Iaur", "Anorian", "Ithilien", "Lossoth", "Snow-men of Forochel", "Angmar", "Carn Dum", "Forodwaith", "Northern Waste", "Ered Mithrin", "Grey Mountains", "Withered Heath", "Mount Gundabad", "High Pass", "Goblin-town", "Eagles' Eyrie", "Carrock", "Beorn's House", "Forest River", "Long Lake", "Celduin", "River Running", "Carnen", "Redwater", "Iron Hills", "Erebor", "Lonely Mountain", "Ravenhill", "Front Gate", "Arkenstone", "Heart of the Mountain", "King Under the Mountain", "Thror", "Thrain", "Thorin Oakenshield", "Fili", "Kili", "Balin", "Dwalin", "Oin", "Gloin", "Bifur", "Bofur", "Bombur", "Dori", "Nori", "Ori", "Dain Ironfoot", "Dis", "Dwarven Hoard", "Seven Rings", "Nine Rings", "Three Rings", "Gwaith-i-Mirdain", "Celebrimbor", "Annatar", "Lord of Gifts", "Master of the Ring", "Eye of Barad-dur", "Dark Tower", "Shadow of the East", "Shadow of the Past", "Long-expected Party", "Shadow of Mordor", "Land of Shadow", "Mount of Fire", "Sammath Naur", "Cracks of Doom", "Doom of the Ring", "Destruction of the Ring", "Victory of the West", "King Elessar", "High King", "King of Arnor", "King of Gondor", "Reunited Kingdom", "Steward's Rod", "White Tree of Gondor", "Dead Tree", "Sapling of the White Tree", "Mindolluin", "Mount Tarlang", "Ered Nimrais", "White Mountains", "Blackroot Vale", "Morthond", "Ringlo", "Gilrain", "Serni", "Sirith", "Celos", "Poros", "Harnen", "Crossroads", "Statue of the King", "Henneth Annun", "Window on the West", "Forbidden Pool", "Slag-mounds", "Tower of the Moon", "Tower of the Rising Moon", "Tower of Sorcery", "Tower of the Setting Sun", "Tower of Guard", "Tower of Anor", "Tower of Minas Ithil", "Tower of Minas Anor", "Seven Stars and Seven Stones", "One White Tree", "Elendilmir", "Star of the North", "Heir of Isildur", "Heir of Elendil", "Standard of Elendil", "White Tree and Seven Stars", "Crowned Swan", "Black Banner", "Red Eye", "White Hand", "S. Blood-hand", "Saruman the White", "Saruman of Many Colors", "Curunir", "The Skillful", "Grey Wanderer", "Stormcrow", "Messenger of Ill News", "Lathspell", "Ill-news", "Wormtongue", "Poison-counsel", "King's Counselor", "Golden Hall", "House of Eorl", "Mark of the Rohirrim", "Riddermark", "Horse-lords", "Masters of Horses", "Strawheads", "Forgoil", "White-skins", "Tribute of Horses", "Mearas", "Prince of Horses", "Snowmane", "Hasufel", "Arod", "Stybba", "Firefoot", "Windfola", "Brego", "Felarof", "Father of Horses", "Mighty Steed", "War-steed", "Cavalry of Rohan", "Shield-maiden", "White Lady of Rohan", "Lady of the Shield-arm", "Lady of Ithilien", "Princess of Gondor", "Prince Faramir", "Steward Faramir", "Captain of the White Tower", "Captain-General", "Lord of the Mark", "King of the Golden Hall", "Mortal Lands", "Outer Lands", "Hither Lands", "Westernesse", "Land of the Star", "Land of Shadow", "Nameless Land", "Land of the Halflings", "The Shire", "Four Farthings", "North Farthing", "South Farthing", "East Farthing", "West Farthing", "The Marches", "The Downs", "The Wild", "Wilderness", "Lone-lands", "Angle", "Trollshaws", "Ettenmoors", "Coldfells", "Hoarwell", "Mitheithel", "Bruinen", "Loudwater", "Last Bridge", "Great East Road", "Greenway", "North Road", "South Road", "Cross-roads", "Gate of the Dead", "Paths of the Dead", "Dark Door", "Stone of Erech", "Hill of Erech", "Morthond Vale", "Blackroot", "White Mountains", "Ered Nimrais", "Seven Rivers of Gondor", "Five Streams of Lebennin", "Ethir Anduin", "Mouths of Anduin", "Bay of Belfalas", "Sea of Nurn", "Sea of Helcar", "Sea of Rhun", "Inland Sea", "East", "West", "North", "South", "Dawn", "Dusk", "Night", "Day", "Sunlight", "Starlight", "Moonlight", "Elbereth", "Gilthoniel", "Varda", "Queen of the Stars", "Star-kindler", "Manwe", "Lord of the Air", "Ulmo", "Lord of the Waters", "Aule", "The Smith", "Yavanna", "Giver of Fruits", "Orome", "The Hunter", "Mandos", "Keeper of the Dead", "Namo", "Nienna", "Lady of Mercy", "Estë", "Vaire", "Vana", "Nessa", "Tulkas", "Strongest of the Valar", "Melkor", "The Rebel", "Dark Power", "Great Enemy", "First Enemy", "Bane of Middle-earth", "Shadow of the World", "Corruption", "Taint", "Evil", "Darkness", "Light", "Fire", "Ice", "Stone", "Iron", "Gold", "Silver", "Mithril", "True-silver", "Morian-silver", "Dwarf-gold", "Elf-glass", "Star-glass", "Light of Earendil", "Evening Star", "Morning Star", "Earendil the Mariner", "Sky-ship", "Vingilot", "Flower of Foam", "Silmaril of the Sky", "Hopes of Men", "Salvation", "Fellowship of the Ring", "Nine Walkers", "Nine Riders", "Black Riders", "Wraiths on Wings", "Fell Beasts", "Hell-hawks", "Steeds of Mordor", "Black Horses", "Morgul-steel", "Witch-king of Angmar", "Lord of the Nazgul", "Captain of Despair", "The Dwimmerlaik", "King of the Nine", "Undead", "Spectral", "Ghostly", "Phantom", "Apparition", "Shade", "Spirit", "Barrow-wight", "Cold-hand", "Wight-fire", "Barrow-downs", "Tyrn Gorthad", "Ancient Graves", "Dagger of Westernesse", "Barrow-blade", "Tom's Song", "Bombadillo", "Old Man Willow", "Withywindle", "Forest-river", "Bonfire Glade", "Great Willow", "Deep-root", "Night-shiver", "Fear", "Hope", "Courage", "Valor", "Honor", "Betrayal", "Greed", "The Ring's Lure", "Corruption of the Heart", "Strength of Will", "Small Things", "Great Deeds", "Victory", "Sacrifice", "End of All Things"
    ],
    "Pokemon" : [
        "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle", "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree", "Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate", "Spearow", "Fearow", "Ekans", "Arbok", "Pikachu", "Raichu", "Sandshrew", "Sandslash", "Nidoran♀", "Nidorina", "Nidoqueen", "Nidoran♂", "Nidorino", "Nidoking", "Clefairy", "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff", "Zubat", "Golbat", "Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth", "Diglett", "Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck", "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam", "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel", "Geodude", "Graveler", "Golem", "Ponyta", "Rapidash", "Slowpoke", "Slowbro", "Magnemite", "Magneton", "Farfetch'd", "Doduo", "Dodrio", "Seel", "Dewgong", "Grimer", "Muk", "Shellder", "Cloyster", "Gastly", "Haunter", "Gengar", "Onix", "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak", "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey", "Tangela", "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu", "Starmie", "Mr. Mime", "Scyther", "Jynx", "Electabuzz", "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados", "Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", "Kabutops", "Aerodactyl", "Snorlax", "Articuno", "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew", "Chikorita", "Bayleef", "Meganium", "Cyndaquil", "Quilava", "Typhlosion", "Totodile", "Croconaw", "Feraligatr", "Sentret", "Furret", "Hoothoot", "Noctowl", "Ledyba", "Ledian", "Spinarak", "Ariados", "Crobat", "Chinchou", "Lanturn", "Pichu", "Cleffa", "Igglybuff", "Togepi", "Togetic", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Bellossom", "Marill", "Azumarill", "Sudowoodo", "Politoed", "Hoppip", "Skiploom", "Jumpluff", "Aipom", "Sunkern", "Sunflora", "Yanma", "Wooper", "Quagsire", "Espeon", "Umbreon", "Murkrow", "Slowking", "Misdreavus", "Unown", "Wobbuffet", "Girafarig", "Pineco", "Forretress", "Dunsparce"
    ],
    "Jobs (PT)" : [
        "Abade", "Abóbada", "Acompanhante de Idosos", "Acupuntor", "Adestrador", "Administrador de Condomínios", "Administrador de Empresas", "Administrador de Redes", "Administrador Hospitalar", "Administrador Público", "Advogado", "Advogado de Família", "Advogado Criminalista", "Aferidor", "Afiador", "Agente de Execução", "Agente de Navegação", "Agente de Viagens", "Agente Funerário", "Agente Imobiliário", "Agente Judicial", "Agente Literário", "Agente Marítimo", "Agente Publicitário", "Agrónomo", "Ajudante de Cozinha", "Ajudante de Lar", "Ajudante de Mecânico", "Ajudante de Padeiro", "Alfaiate", "Alfeire", "Algalreador", "Almofala", "Almoxarife", "Alpinista Industrial", "Amolador", "Analista de Dados", "Analista de Investimentos", "Analista de Marketing Digital", "Analista de Negócios", "Analista de Qualidade", "Analista de Recursos Humanos", "Analista de Risco", "Analista de Sistemas", "Analista Financeiro", "Analista Funcional", "Analista Político", "Anestesista", "Angariador Imobiliário", "Animador Cultural", "Animador de Rua", "Animador Sociocultural", "Antropólogo", "Apicultor", "Apontador", "Apresentador de Televisão", "Aquicultor", "Armador", "Armador de Ferro", "Armazenista", "Arqueólogo", "Arquiteto", "Arquiteto de Interiores", "Arquiteto de Paisagem", "Arquiteto Naval", "Arquiteto Urbanista", "Arquivista", "Arrais", "Arrematante", "Artesão", "Artífice", "Artista Plástico", "Ascensorista", "Assessor de Imprensa", "Assessor Jurídico", "Assistente Administrativo", "Assistente de Bordo", "Assistente de Consultório", "Assistente de Direção", "Assistente de Geriatria", "Assistente de Marketing", "Assistente de Recintos Desportivos", "Assistente Operacional", "Assistente Social", "Assoalhador", "Astrólogo", "Astrónomo", "Ator", "Atuário", "Auditor", "Auditor de Sistemas", "Auditor Financeiro", "Auditor Público", "Auxiliar de Ação Educativa", "Auxiliar de Ação Médica", "Auxiliar de Enfermagem", "Auxiliar de Farmácia", "Auxiliar de Limpeza", "Auxiliar de Veterinária", "Avaliador de Arte", "Avaliador de Imóveis", "Avaliador de Joias", "Azeiteiro", "Azulejador", "Bailarino", "Baixista", "Bancário", "Barbeiro", "Barman", "Bate-chapas", "Bibliotecário", "Bibliógrafo", "Biogeneticista", "Biólogo", "Biólogo Marinho", "Biomédico", "Bioquímico", "Biotecnólogo", "Blogger", "Bombeiro", "Bombeiro Sapador", "Bonequeiro", "Bordadora", "Botânico", "Broker", "Cabeleireiro", "Cabo de Mar", "Caçador", "Caixa d'Água", "Calceteiro", "Caldeireiro", "Calígrafo", "Câmara de Vídeo", "Cambista", "Caminhoneiro", "Campino", "Canalizador", "Cantor", "Capataz", "Capelão", "Capitão de Mar-e-Guerra", "Capitão de Navio", "Cardiologista", "Cardiopneumologista", "Carpinteiro", "Carpinteiro de Limpos", "Carpinteiro de Toscos", "Carregador", "Carreteiro", "Carteiro", "Cartógrafo", "Cartonageiro", "Casamenteiro", "Caseiro", "Castrador", "Catador", "Catequista", "Cavalariço", "Cenógrafo", "Ceramista", "Cesteiro", "Chapeleiro", "Chaveiro", "Chefe de Cozinha", "Chefe de Fila", "Chefe de Oficina", "Chefe de Sala", "Choqueiro", "Cientista", "Cientista de Dados", "Cientista Político", "Cientista Social", "Cinematógrafo", "Cirurgião", "Cirurgião Dentista", "Cirurgião Plástico", "Citologista", "Climatologista", "Cobrador de Bilhetes", "Cobrador de Fraudes", "Codificador", "Comandante de Aeronave", "Comandante de Navio", "Comerciante", "Comissário de Bordo", "Comissário de Polícia", "Compositor", "Comprador", "Contabilista", "Contabilista Certificado", "Contínuo", "Controlador Aéreo", "Controlador de Gestão", "Controlador de Qualidade", "Controlador de Tráfego", "Conservador de Museu", "Conservador de Registo Civil", "Consultor de Gestão", "Consultor de Imagem", "Consultor de Informática", "Consultor de Marketing", "Consultor de Negócios", "Consultor de Seguros", "Consultor de Viagens", "Consultor Fiscal", "Consultor Imobiliário", "Consultor Sap", "Copywriter", "Coreógrafo", "Coronel", "Corretor de Bolsa", "Corretor de Imóveis", "Corretor de Seguros", "Corticeiro", "Costureira", "Coveiro", "Cozinheiro", "Cozinheiro de Primeira", "Cozinheiro de Segunda", "Cratonista", "Crítico de Arte", "Crítico de Cinema", "Crítico de Gastronomia", "Crítico Literário", "Cromador", "Cronista", "Curador de Arte", "Dactilógrafo", "Damasquino", "Dancista", "Data Scientist", "Decorador", "Defensor Público", "Degustador", "Delegado Comercial", "Delegado de Saúde", "Demógrafo", "Dentista", "Deputado", "Dermatologista", "Desenhador", "Desenhador de Construção Civil", "Desenhador de Máquinas", "Desenhador Projetista", "Designer de Comunicação", "Designer de Equipamento", "Designer de Interiores", "Designer de Moda", "Designer de Produto", "Designer de Videojogos", "Designer Gráfico", "Designer Industrial", "Designer Multimedia", "Designer UX/UI", "Despachante Alfandegário", "Despachante Oficial", "Detetive Privado", "Detetive Repercussivo", "Dietista", "Digital Marketer", "Diplomata", "Diretor Comercial", "Diretor de Arte", "Diretor de Cinema", "Diretor de Escola", "Diretor de Fotografia", "Diretor de Marketing", "Diretor de Produção", "Diretor de Recursos Humanos", "Diretor Financeiro", "Diretor Geral", "Diretor Logístico", "Diretor Operacional", "Diretor Técnico", "Dizedor", "Doutor", "Dramaturgo", "Ecologista", "Economista", "Economista Agrário", "Editor", "Editor de Imagem", "Editor de Livros", "Editor de Vídeo", "Educador de Infância", "Educador Social", "Eletricista", "Eletricista de Auto", "Eletricista de Construção", "Eletricista de Manutenção", "Eletromecânico", "Embaixador", "Embalsamador", "Emoldurador", "Empalador", "Empregado Bancário", "Empregado de Balcão", "Empregado de Escritório", "Empregado de Limpeza", "Empregado de Mesa", "Empreiteiro", "Encadernador", "Encarregado de Obra", "Endocrinologista", "Enfermeiro", "Enfermeiro de Cuidados Intensivos", "Enfermeiro de Família", "Enfermeiro de Saúde Materna", "Enfermeiro de Saúde Mental", "Enfermeiro de Urgência", "Enfermeiro do Trabalho", "Enfermeiro Especialista", "Enfermeiro Geral", "Engenheiro Aeroespacial", "Engenheiro Agrónomo", "Engenheiro Alimentar", "Engenheiro Biomédico", "Engenheiro Civil", "Engenheiro de Ambiente", "Engenheiro de Computadores", "Engenheiro de Controle e Automação", "Engenheiro de Gestão Industrial", "Engenheiro de Materiais", "Engenheiro de Minas", "Engenheiro de Produção", "Engenheiro de Redes", "Engenheiro de Segurança", "Engenheiro de Software", "Engenheiro de Telecomunicações", "Engenheiro Eletrotécnico", "Engenheiro Físico", "Engenheiro Florestal", "Engenheiro Geólogo", "Engenheiro Industrial", "Engenheiro Informático", "Engenheiro Mecânico", "Engenheiro Mecatrónico", "Engenheiro Metalúrgico", "Engenheiro Naval", "Engenheiro Polímero", "Engenheiro Químico", "Engenheiro Têxtil", "Enólogo", "Entalhador", "Entomologista", "Entregador", "Epidemiologista", "Epigrafista", "Equitador", "Escrivão", "Escritor", "Escultor", "Especialista de Marketing", "Especialista de SEO", "Especialista em Cibersegurança", "Especialista em Logística", "Espeleólogo", "Estafeta", "Estatístico", "Esteticista", "Estivador", "Estofador", "Estomatologista", "Estrategista Digital", "Estuador", "Etnógrafo", "Etnólogo", "Executivo de Contas", "Excursionista", "Explicador", "Extração de Cortiça", "Fábrica de Conservas", "Falsificador", "Farmacêutico", "Farmacêutico Hospitalar", "Faxineiro", "Feirante", "Ferreiro", "Ferramenteiro", "Fiador", "Figurinista", "Filólogo", "Filósofo", "Fiscal de Atividades Económicas", "Fiscal de Finanças", "Fiscal de Obras", "Fiscal de Transportes", "Físico", "Físico Nuclear", "Fisioterapeuta", "Fisiologista", "Fiteiro", "Florista", "Fogueteiro", "Folclorista", "Fonoaudiólogo", "Fontanário", "Forneiro", "Fotógrafo", "Fotógrafo de Moda", "Fotógrafo de Natureza", "Fotógrafo de Publicidade", "Fotógrafo Social", "Fotojornalista", "Fresador", "Fruteiro", "Funchalense", "Funcionário Público", "Fundidor", "Fuzileiro", "Gabinete de Estudos", "Gaitista", "Galaico", "Galvanizador", "Ganadeiro", "Garagista", "Gari", "Garimpeiro", "Garçom", "Gastrónomo", "Gastroenterologista", "Genealogista", "General", "Geneticista", "Geodesista", "Geofísico", "Geógrafo", "Geólogo", "Geómetra", "Gerente de Banco", "Gerente de Loja", "Gerente de Projeto", "Geriatra", "Gestor de Ativos", "Gestor de Clientes", "Gestor de Comunidade", "Gestor de Conteúdos", "Gestor de Contas", "Gestor de Crise", "Gestor de Eventos", "Gestor de Formação", "Gestor de Frota", "Gestor de Manutenção", "Gestor de Marketing", "Gestor de Património", "Gestor de Produto", "Gestor de Projeto", "Gestor de Qualidade", "Gestor de Redes Sociais", "Gestor de Recursos Humanos", "Gestor de Resíduos", "Gestor de Sistemas", "Gestor de Tráfego", "Gestor de Vendas", "Gestor Financeiro", "Gestor Hoteleiro", "Gestor Imobiliário", "Gestor Logístico", "Gestor Público", "Gestor Turístico", "Ginecologista", "Gira-discos", "Glaceador", "Goleiro", "Governanta", "Gráfico", "Gravador", "Grumete", "Guarda de Segurança", "Guarda Florestal", "Guarda Noturno", "Guarda Prisional", "Guarda-Fios", "Guarda-Livros", "Guarda-Marinha", "Guarda-Redes", "Guia de Montanha", "Guia de Museus", "Guia Intérprete", "Guia Turístico", "Guitarrista", "Halterofilista", "Harmonizador", "Harpista", "Hematologista", "Hepatologista", "Herborista", "Hidráulico", "Hidrogeólogo", "Hidrólogo", "Higienista Oral", "Hipo-terapeuta", "Historiador", "Historiador de Arte", "Homeopata", "Horticultor", "Hospedeira de Bordo", "Hospedeira de Eventos", "Hospitalário", "Hostess", "Ictiólogo", "Iluminador", "Ilustrador", "Imagens Médicas", "Imunologista", "Impressor", "Injetor", "Inquiridor", "Inseminador Artificial", "Inspecionador", "Inspetor de Polícia", "Inspetor de Qualidade", "Inspetor de Saúde", "Inspetor de Trabalho", "Inspetor Escolar", "Inspetor Finanças", "Inspetor Pesca", "Instalador de Ar Condicionado", "Instalador de Painéis Solares", "Instalador de Redes", "Instrutor de Condução", "Instrutor de Fitness", "Instrutor de Ioga", "Instrutor de Mergulho", "Instrutor de Pilotagem", "Instrutor de Surf", "Instrutor de Voo", "Instrumentista", "Intérprete", "Intérprete de Língua Gestual", "Investigador Científico", "Investigador Criminal", "Investigador de Mercado", "Investidor", "Janela", "Jardineiro", "Jornalista", "Jornalista Desportivo", "Jornalista Político", "Jornaleiro", "Jóquei", "Juiz", "Juiz de Direito", "Juiz de Linha", "Juiz de Paz", "Jurista", "Lactarista", "Ladrilhador", "Lagoneiro", "Lanterneiro", "Lapidador", "Lavadeiro", "Lavrador", "Leiloeiro", "Leiteiro", "Leme", "Léxico", "Lexicógrafo", "Librário", "Licenciado", "Lidador", "Limpador de Vidros", "Linguista", "Linotipista", "Lixeiro", "Lobbyista", "Locutor de Rádio", "Logista", "Logístico", "Logopeda", "Lojista", "Lurista", "Lutador", "Luthier", "Madrinha de Guerra", "Maestro", "Magistrado", "Maid", "Mailhador", "Mailhista", "Mainate", "Maquilhadora", "Maquinista de Comboios", "Maquinista de Cinema", "Marceneiro", "Mareante", "Marinheiro", "Marketing Manager", "Marmorista", "Martelador", "Massagista", "Massoterapeuta", "Matemático", "Mecânico de Automóveis", "Mecânico de Aviões", "Mecânico de Bicicletas", "Mecânico de Motos", "Mecânico Industrial", "Mecatrónico", "Mediador de Conflitos", "Mediador de Seguros", "Mediador Imobiliário", "Médico de Clínica Geral", "Médico de Família", "Médico Dentista", "Médico do Trabalho", "Médico Forense", "Médico Internista", "Médico Legista", "Médico Militar", "Médico Pediatra", "Médico Veterinário", "Medidor", "Mergulhador", "Mestre de Cerimónias", "Mestre de Obras", "Mestre-Escola", "Metalúrgico", "Meteorologista", "Microbiologista", "Microeletrónico", "Militar", "Mineiro", "Ministro", "Modelista", "Modelo", "Moleiro", "Monitor de ATL", "Monitor de Desporto", "Montador de Estruturas", "Mordomo", "Motorista de Pesados", "Motorista de Táxi", "Motorista de TVDE", "Motorista Particular", "Museólogo", "Músico", "Musicoterapeuta", "Nadador-Salvador", "Nanotecnólogo", "Narrador", "Naturista", "Naturopata", "Navegador", "Nefrologista", "Negociador", "Neurocirurgião", "Neurologista", "Neuropsicólogo", "Notário", "Nutricionista", "Nutrólogo", "Obstetra", "Oceanógrafo", "Oculista", "Odontologista", "Oficial de Diligências", "Oficial de Justiça", "Oficial de Marinha", "Oficial de Notariado", "Oficial de Registo", "Olaria", "Oleiro", "Oncologista", "Operador de Armazém", "Operador de Caixa", "Operador de Call Center", "Operador de Câmara", "Operador de Empilhador", "Operador de Estação de Tratamento", "Operador de Gráfica", "Operador de Grua", "Operador de Máquinas", "Operador de Marketing", "Operador de Produção", "Operador de Raio-X", "Operador de Sondagens", "Operador de Telecomunicações", "Operador de Tráfego", "Operador de Turismo", "Operador Ecológico", "Operador Fabril", "Operador Ferroviário", "Operador Logístico", "Operário", "Operário Civil", "Operário de Construção", "Oportunista", "Optometrista", "Orador", "Orçamentista", "Organista", "Organizador de Casamentos", "Organizador de Eventos", "Orientador Educativo", "Orientador Profissional", "Ornitólogo", "Ortodontista", "Ortopedista", "Ortoptista", "Osteopata", "Otorrinolaringologista", "Ourives", "Ouvidor", "Padeiro", "Padre", "Paisagista", "Paleógrafo", "Paleontólogo", "Palhaço", "Panteísta", "Papeleiro", "Paraquedista", "Paramédico", "Parceiro de Negócios", "Pároco", "Partidista", "Passador", "Pastelheiro", "Pastor", "Patologista", "Patologista Clínico", "Patrão de Pesca", "Pecuarista", "Pedagogo", "Pediatra", "Pedreiro", "Pedólogo", "Peixeiro", "Peluqueiro", "Penhorista", "Pensionista", "Perfumista", "Perito Agrícola", "Perito Averiguador", "Perito Contabilista", "Perito Criminal", "Perito de Arte", "Perito de Seguros", "Perito Judicial", "Personal Trainer", "Pescador", "Pesquisador", "Pianista", "Piloto de Automóveis", "Piloto de Aviação Civil", "Piloto de Helicópteros", "Piloto de Linha Aérea", "Piloto de Testes", "Pintor", "Pintor Artístico", "Pintor de Automóveis", "Pintor de Construção Civil", "Piscicultor", "Pneumologista", "Podologista", "Poeta", "Polícia", "Polícia Judiciária", "Polícia Municipal", "Político", "Polidor", "Pontoneiro", "Porteiro", "Praticante de Direito", "Pregador", "Prensista", "Preparador de Obra", "Presidente", "Procurador", "Produtor Agrícola", "Produtor de Cinema", "Produtor de Espetáculos", "Produtor de Eventos", "Produtor de Moda", "Produtor de Música", "Produtor de Televisão", "Produtor Executivo", "Professor de Artes", "Professor de Desporto", "Professor de História", "Professor de Línguas", "Professor de Música", "Professor de Primária", "Professor de Secundário", "Professor Universitário", "Programador de Aplicações", "Programador de Back-end", "Programador de Front-end", "Programador de Java", "Programador de Jogos", "Programador de Sistemas", "Programador Web", "Projetista", "Promotor de Vendas", "Propagandista", "Protético", "Psicólogo", "Psicólogo Clínico", "Psicólogo Educacional", "Psicólogo Organizacional", "Psicomotricista", "Psicopedagogo", "Psiquiatra", "Publicitário", "Puericultor", "Puxador", "Quadro Superior", "Químico", "Químico Analítico", "Químico Industrial", "Quirurgião", "Quiroprático", "Radialista", "Radiologista", "Radioterapeuta", "Rancheiro", "Reabilitador Social", "Reanimador", "Realizador de Cinema", "Realizador de Televisão", "Rececionista", "Rececionista de Hotel", "Recrutador", "Redator", "Redator Publicitário", "Regedor", "Regente Agrícola", "Regente de Banda", "Regente de Orquestra", "Religioso", "Relojoeiro", "Relações Públicas", "Repórter", "Repórter de Imagem", "Repositor", "Representante Comercial", "Representante de Vendas", "Restaurador de Arte", "Restaurador de Livros", "Revisor", "Revisor de Provas", "Revisor Oficial de Contas", "Rigger", "Roteirista", "Roupeiro", "Sacerdote", "Saguão", "Salgador", "Salva-vidas", "Sapateiro", "Sargento", "Sastreador", "Saúde Pública", "Scouter", "Secretário", "Secretário de Direção", "Secretário Executivo", "Secretário Jurídico", "Segurança", "Segurança Informática", "Seireiro", "Semeador", "Semicondutores", "Senador", "Sereiro", "Serralheiro", "Serralheiro Civil", "Serralheiro Mecânico", "Servente de Pedreiro", "Sexólogo", "Siderúrgico", "Sindicalista", "Sismólogo", "Sociólogo", "Socorrista", "Software Engineer", "Solicitador", "Sommelier", "Sondador", "Sonoplasta", "Soprano", "Soviético", "Steward", "Superintendente", "Supervisor", "Supervisor de Produção", "Supervisor de Vendas", "Tabelião", "Tanoeiro", "Taquígrafo", "Tatuador", "Taxidermista", "Taxista", "Tecedor", "Técnico Agrícola", "Técnico Administrativo", "Técnico Comercial", "Técnico de Som", "Técnico de Farmácia", "Técnico de Gás", "Técnico de Informática", "Técnico de Laboratório", "Técnico de Logística", "Técnico de Luz", "Técnico de Manutenção", "Técnico de Marketing", "Técnico de Ortótica", "Técnico de Prótese Dentária", "Técnico de Radiologia", "Técnico de Reciclagem", "Técnico de Recursos Humanos", "Técnico de Refrigeração", "Técnico de Saúde", "Técnico de Segurança", "Técnico de Seguros", "Técnico de Telecomunicações", "Técnico de Turismo", "Técnico de Vendas", "Técnico Eletrónico", "Técnico Eletrotécnico", "Técnico Financeiro", "Técnico Florestal", "Técnico Geriátrico", "Técnico Hospitalar", "Técnico Industrial", "Técnico Judiciário", "Técnico Jurídico", "Técnico Mecânico", "Técnico Oficial de Contas", "Técnico ótico", "Técnico Químico", "Técnico Radiologista", "Técnico Superior", "Técnico Veterinário", "Televendas", "Teólogo", "Terapeuta", "Terapeuta da Fala", "Terapeuta Familiar", "Terapeuta Ocupacional", "Tesoureiro", "Têxtil", "Tintureiro", "Tipógrafo", "Topógrafo", "Torneiro", "Torneiro Mecânico", "Tosquiador", "Trabalhador Agrícola", "Trabalhador de Construção", "Trabalhador Social", "Tradutor", "Tradutor Juramentado", "Trancista", "Tratador de Animais", "Treinador de Animais", "Treinador de Futebol", "Treinador Desportivo", "Tricotador", "Tripulante de Cabine", "Trompetista", "Turismólogo", "Urbanista", "Urologista", "UX Designer", "Velejador", "Vendedor", "Vendedor Ambulante", "Vendedor de Automóveis", "Vendedor de Loja", "Vendedor Técnico", "Veneireiro", "Ventoinheiro", "Vereador", "Veterinário", "Vicediretor", "Vidreiro", "Vigilante", "Vigilante de Natureza", "Violoncelista", "Violonista", "Virolo", "Viticultor", "Vitrinista", "Vocalista", "Vogal", "Voz-off", "Web Designer", "Web Developer", "Webmaster", "Xerife", "Xilógrafo", "Zelador", "Zootecnista"
    ],
    "Animated Movies" : [
        "Snow White and the Seven Dwarfs (Branca de Neve e os Sete Anões)",
        "Pinocchio (Pinóquio)",
        "Fantasia",
        "Dumbo",
        "Bambi",
        "Cinderella",
        "Alice in Wonderland (Alice no País das Maravilhas)",
        "Peter Pan",
        "Lady and the Tramp (A Dama e o Vagabundo)",
        "Sleeping Beauty (A Bela Adormecida)",
        "One Hundred and One Dalmatians (101 Dálmatas)",
        "The Sword in the Stone (A Espada Era a Lei)",
        "The Jungle Book (O Livro da Selva)",
        "The Aristocats (Os Aristogatos)",
        "Robin Hood",
        "The Rescuers (As Aventuras de Bernardo e Bianca)",
        "The Fox and the Hound (Papuça e Dentuça)",
        "The Little Mermaid (A Pequena Sereia)",
        "Beauty and the Beast (A Bela e o Monstro)",
        "Aladdin",
        "The Lion King (O Rei Leão)",
        "Pocahontas",
        "Toy Story",
        "The Hunchback of Notre Dame (O Corcunda de Notre Dame)",
        "Hercules",
        "Mulan",
        "A Bug's Life (Uma Vida de Inseto)",
        "Tarzan",
        "Toy Story 2",
        "Monsters, Inc. (Monstros e Companhia)",
        "Lilo & Stitch",
        "Treasure Planet (O Planeta do Tesouro)",
        "Finding Nemo (À Procura de Nemo)",
        "Brother Bear (Irmão Urso)",
        "The Incredibles",
        "Cars (Carros)",
        "Ratatouille",
        "WALL-E",
        "Bolt",
        "Up (Up - Altamente!)",
        "The Princess and the Frog (A Princesa e o Sapo)",
        "Toy Story 3",
        "Tangled (Entrelaçados)",
        "Cars 2 (Carros 2)",
        "Brave (Brave - Indomável)",
        "Wreck-It Ralph (Força Ralph!)",
        "Monsters University (A Universidade dos Monstros)",
        "Frozen",
        "Big Hero 6",
        "Inside Out (Divertida-Mente)",
        "The Good Dinosaur (A Viagem de Arlo)",
        "Zootopia (Zootrópolis)",
        "Finding Dory (À Procura de Dory)",
        "Moana (Vaiana)",
        "Cars 3 (Carros 3)",
        "Coco",
        "Incredibles 2 (Os Incríveis 2)",
        "Ralph Breaks the Internet (Ralph VS Internet)",
        "Toy Story 4",
        "Frozen II",
        "Onward (Bora Lá)",
        "Soul (Soul - Uma Aventura com Alma)",
        "Raya and the Last Dragon (Raya e o Último Dragão)",
        "Luca",
        "Encanto",
        "Turning Red (Turning Red - Estranhamente Vermelho)",
        "Lightyear",
        "Strange World (Estranho Mundo)",
        "Elemental",
        "Wish",
        "Inside Out 2 (Divertida-Mente 2)",
        "Elio"
    ],

    "Celebrities": [
  "Cristiano Ronaldo",
  "Madonna",
  "Amália Rodrigues",
  "Eusébio",
  "Angelina Jolie",
  "Brad Pitt",
  "Marilyn Monroe",
  "Elvis Presley",
  "Joaquim de Almeida",
  "Sara Sampaio",
  "Daniela Ruah",
  "Tom Cruise",
  "Meryl Streep",
  "Lady Gaga",
  "Beyoncé",
  "Salvador Sobral",
  "Mariza",
  "Freddie Mercury",
  "Michael Jackson",
  "Pelé",
  "Ayrton Senna",
  "Lewis Hamilton",
  "José Mourinho",
  "Nelly Furtado",
  "Camilo Castelo Branco",
  "Fernando Pessoa",
  "Eça de Queirós",
  "Sophia de Mello Breyner",
  "Vasco da Gama",
  "Luís Vaz de Camões",
  "Robert De Niro",
  "Al Pacino",
  "Scarlett Johansson",
  "Leonardo DiCaprio",
  "Julia Roberts",
  "Tom Hanks",
  "Morgan Freeman",
  "Rihanna",
  "Taylor Swift",
  "Adele",
  "Ed Sheeran",
  "David Beckham",
  "Victoria Beckham",
  "Will Smith",
  "Denzel Washington",
  "Keanu Reeves",
  "Johnny Depp",
  "Harrison Ford",
  "Arnold Schwarzenegger",
  "Sylvester Stallone",
  "Bruce Willis",
  "Jennifer Aniston",
  "George Clooney",
  "Cate Blanchett",
  "Nicole Kidman",
  "Penélope Cruz",
  "Javier Bardem",
  "António Banderas",
  "Shakira",
  "Jennifer Lopez",
  "Britney Spears",
  "Justin Timberlake",
  "Justin Bieber",
  "The Weeknd",
  "Dua Lipa",
  "Billie Eilish",
  "Elon Musk",
  "Bill Gates",
  "Mark Zuckerberg",
  "Jeff Bezos",
  "Stephen Hawking",
  "Albert Einstein",
  "Charles Darwin",
  "Nelson Mandela",
  "Dalai Lama",
  "Papa Francisco",
  "Rainha Isabel II",
  "Príncipe William",
  "Harry Styles",
  "Zendaya",
  "Timothée Chalamet",
  "Margot Robbie",
  "Cillian Murphy",
  "Robert Downey Jr.",
  "Benedict Cumberbatch",
  "Emma Watson",
  "Daniel Radcliffe",
  "Ryan Gosling",
  "Joaquin Phoenix",
  "Natalie Portman",
  "Princesa Diana",
  "Mick Jagger",
  "Paul McCartney",
  "Elton John",
  "David Bowie",
  "Amy Winehouse",
  "Kurt Cobain",
  "Bob Marley",
  "Bruce Springsteen",
  "Patti Smith"
    ],

};


const mimicSettings = {
    identifier: 'mimic',
    title: 'Word Game',
    newScore: `
<select id="language" class="absolute absolute--thirdish">${Object.keys(words).map(lang => `<option value="${lang}">${lang}</option>`).join('')}</select>
<table id="board" class="board board--table"></table>
<div class="section mb-1 w-full">
    <div class="section section--row w-full">
        <button class="button button--big button--danger" id="skipBtn">Skip</button>
        <div class="word" id="word">Confirm to start!</div>
        <button class="button button--big button--primary" id="confirmBtn">Confirm</button>
    </div>
</div>
`,
    howToPlay: JSON.stringify({
        intro: 'Neste jogo de mimica, cada jogador tem 1 minuto para fazer mímica do máximo numero de palavras possível.',
        rules: [
            'Escolhe um tema, o numero e nome das equipas e começa a jogar.',
            'Se a equipa acertar na palavra, clica em "Confirm" e ganham um ponto',
            'Se a equipa, ou o jogador não conseguirem acertar podem perder um ponto para saltar a palavra clicando no botão "Skip"',
            'Ao fim de um minuto, devem passar a vez à equipa adversária',
        ],
        conclusion: 'Podem jogar tantas vezes quantas quiserem. No fim ganha a equipa com mais pontos.',
    }),
};

export default mimicSettings;

